kasa/cli.py, kasa/discover.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartplug.py, kasa/smartstrip.py, kasa/tests/conftest.py, kasa/tests/test_fixtures.py, tox.ini
* Closes #12 and #7
* Converts cli to use asyncio.run() where needed.
* The children from smartstrips is being initialized during the first update call.
=> Remove sync interface, add asyncio discovery

kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartplug.py, kasa/smartstrip.py
For regular devices, device_id is the mac address and for child devices it is a combination of the mac address and the child_id.
This is simply a helper to simplify the downstream code for homeassistant.
=> Add device_id property, rename context to child_id

kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartplug.py, kasa/smartstrip.py, kasa/tests/conftest.py
The tests are failing for multi-socket devices, the whole piece is much more convoluted than I thought and will require some heavy cleanup..
This will also force other arguments besides the host to be passed explicitly as a kwarg.
=> Cleanup constructors by removing ioloop and protocol arguments

kasa/cli.py
This will remove the unused --save to allow dump_discover to save by default. This will also add a --scrub option to remove personal device details when saving the files.
=> Remove unused save option and add scrubbing

README.md, kasa/tests/fixtures/KP303(UK)_1.0.json
Includes result of `kasa dump-discover` and updates readme to add KP303 as a supported device
=> Adding KP303 to supported devices

kasa/cli.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartplug.py, kasa/smartstrip.py, kasa/tests/conftest.py
* All child device handling is moved out from the main smartdevice class, which simplifies the code.
* This will also cleanup the constructors as only the subdevices require the ID and the parent reference.
* SmartStripPlug offers SmartPlug like interface, but does not allow individual updates
* Trying to update() on the children will cause a warning.
=> Move child socket handling to its own SmartStripPlug class

azure-pipelines.yml, kasa/cli.py, kasa/smartdevice.py, kasa/smartstrip.py
First try to add windows & osx builds to our pipeline.
Closes #30 when it's working.
=> Enable Windows & OSX builds

kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartplug.py, kasa/smartstrip.py, kasa/tests/conftest.py, kasa/tests/test_fixtures.py
The cache was useful trick when the property accesses caused I/O,
which is unnecessary now as dev.update() does explicitly cache results until its called again.
Obsoletes #36.
=> Remove unnecessary cache

README.md, kasa/cli.py, kasa/smartdevice.py
This PR implements "netif" module support, which allows scanning and joining wifi networks even when the device has not been previously provisioned.
* new api to smartdevice: wifi_scan() and wifi_join(ssid, password, keytype)
* cli: new subcommand 'wifi' with two commands: scan and join
```
$ kasa wifi --help
No host name given, trying discovery..
Discovering devices for 3 seconds
Usage: kasa wifi [OPTIONS] COMMAND [ARGS]...
Commands to control wifi settings.
Options:
--help  Show this message and exit.
Commands:
join  Join the given wifi network.
scan  Scan for available wifi networks.
```
Reference: https://github.com/softScheck/tplink-smartplug/blob/master/tplink-smarthome-commands.txt#L65
=> Add commands to control the wifi settings

kasa/cli.py, kasa/protocol.py, kasa/smartdevice.py, kasa/smartstrip.py, kasa/tests/conftest.py, kasa/tests/test_cli.py, kasa/tests/test_fixtures.py, requirements.txt, requirements_test.txt, setup.py, tox.ini
* use asyncclick instead of click, allows defining the commands with async def to avoid manual eventloop/asyncio.run handling
* improve powerstrip support:
* new powerstrip api: `get_plug_by_{name,index}` methods
* cli: fix on/off for powerstrip using the new apis
* add missing update()s for cli's hsv, led, temperature (fixes #43)
* prettyprint the received payloads when debug mode in use
* cli: debug mode can be activated now with `-d`
* powerstriplug now inherits its sysinfo from the parent for easier access (e.g., to mac address of the device).
=> async++, small powerstrip improvements

kasa/smartdimmer.py
According to https://github.com/home-assistant/core/pull/33909/files#diff-9a900d2f83693dd3e01d2894bf1c6bffR452
the dimmers will accept 0 brightness which differs from turning it off
=> Allow 0 brightness for smartdimmer

kasa/smartdevice.py
This is required as https://github.com/PyCQA/pydocstyle/pull/426 does not
fix the issue for async def'd inner functions, causing
```D202: No blank lines allowed after function docstring (found 1)```
The ignores can be removed when https://github.com/PyCQA/pydocstyle/issues/466 gets fixed.
=> Ignore D202 where necessary

kasa/tests/test_cli.py
Flake8 does not error out on my local install (nor did it do for the pre-merge CI checks), I'm not sure why though.
=> Remove unnecessary f-string definition to make tests pass

kasa/discover.py, kasa/smartdevice.py, kasa/smartdimmer.py, kasa/tests/conftest.py, kasa/tests/newfakes.py, kasa/tests/test_discovery.py, kasa/tests/test_fixtures.py
* Adds discovery support for dimmers. Uses the availability of `smartlife.iot.dimmer` for detection, as the type string is the same as for plugs. 
* Adds `is_color` to the common SmartDevice API.
* Remove implicit turn_on call for setting the brightness, less I/O is better.
* Enforces that every new fixture file needs to be added into one of the device type categories for tests.
* Adds tests for discovery's device type detection.
=> Improve dimmer support

README.md, kasa/cli.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartdimmer.py, kasa/smartplug.py, kasa/smartstrip.py, kasa/tests/newfakes.py, kasa/tests/test_cli.py, kasa/tests/test_fixtures.py
A single update() will now fetch information from all interesting modules,
including the current device state and the emeter information.
In practice, this will allow dropping the number of I/O reqs per homeassistant update cycle to 1,
which is paramount at least for bulbs which are very picky about sequential accesses.
This can be further extend to other modules/methods, if needed.
This will also remove the implicit `update()` calls from device state changing methods such as `set_brightness()`. This allows executing multiple changes on a device without unnecessary I/O.
Currently fetched data:
* sysinfo
* realtime, today's and this months emeter stats
New properties:
* emeter_realtime: return the most recent emeter information, update()-version of get_emeter_realtime()
* emeter_today: …
=> Optimize I/O access

kasa/__init__.py, kasa/exceptions.py, kasa/protocol.py, kasa/smartdevice.py, kasa/tests/conftest.py, kasa/tests/test_protocol.py
Add retry logic to protocol class. Defaults to 3 re-tries, so up to 4 queries are automatically tried.
This is based on #63.
Fixes #38
=> Add retries to protocol queries

kasa/smartdimmer.py, kasa/tests/newfakes.py, kasa/tests/test_dimmer.py
* Adds a transition param to set_brightness() that specifies the duration in milliseconds that the dimmer switch will take to transition to the new brightness
This is a stab at the first part of #44.
Closes #44
=> Add transition support for SmartDimmer

kasa/smartbulb.py, kasa/smartdevice.py, kasa/tests/test_bulb.py
This adds `transition` kwarg for all state changing methods.
The values are in milliseconds, and limits of what values are accepted differ likely between devices, so there is no checks for that for now. This has only been tested using the brightness & turn on/off transitions on a KL60.
This is a WIP, as mypy does not like that the signature of `turn_on` and `turn_off` differ, so this does not currently pass the tests and that needs to be investigated.
This PR also changes the setters to return the response from the device, which can potentially be useful for downstream developers:
```
>>> asyncio.run(b.set_brightness(1))
{'on_off': 1, 'mode': 'normal', 'hue': 0, 'saturation': 0, 'color_temp': 2000, 'brightness': 1}
```
I wanted to push this up to give an example how to test the …
=> Bulbs: allow specifying transition for state changes

kasa/cli.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartdimmer.py, kasa/smartplug.py, kasa/smartstrip.py
* `on`, `off`, `hsv`, `temperature` and `brightness` now allow defining `--transition`
* `turn_on` and `turn_on` are now defined now to take `**kwargs` to match with the signatures for dimmers and bulbs.
=> Add --transition to bulb-specific cli commands, fix turn_{on,off} signatures

.readthedocs.yml, README.md
The docs are now automatically generated for PRs and the master using readthedocs.io. The documentation badge & the link in the readme to the apidocs point to the correct location.
=> add .readthedocs.yml required for poetry builds

kasa/discover.py
Some systems (for example dd-wrt routers) requires specifying the network interface name, otherwise the broadcast search does not work. Optional parameter 'interface' added.
Usage example:
```python
devices = asyncio.run(Discover.discover(interface=b'br0'))
for addr, dev in devices.items():
...
```
=> 'Interface' parameter added to discovery process

.gitignore, kasa/cli.py
Fix crash when kasa cli is called with --month or --year arguments.
Per discussions in #102.
=> Update cli.py to addresss crash on year/month calls and improve output formatting

README.md
* add link to tapo p100 project
* fix tplink-smarthome-simulator link
Fixes #83.
=> add tapo link, fix tplink-smarthome-simulator link

README.md
Add reference to https://github.com/flavio-fernandes/mqtt2kasa for users
who may be interested in using MQTT to control/monitor devices managed
by python-kasa
=> README.md: Add link to MQTT interface for python-kasa

.pre-commit-config.yaml, devtools/parse_pcap.py, kasa/__init__.py, kasa/smartdevice.py, kasa/tests/test_emeter.py, kasa/tests/test_readme_examples.py
Fixes #142
Also, update the pre-commit hooks to their newest versions
=> Return None instead of raising an exception on missing, valid emeter keys

devtools/dump_devinfo.py, kasa/cli.py, kasa/discover.py
This modifies the discovery to query only `system:get_sysinfo` as querying multiple modules at once is known to have issues with some devices.
This PR also moves the `dump-devinfo` functionality to a separately shipped file under `devtools`, which should also now allow generating fixture files for devices that do not support querying multiple modules at once.
Fixes #105, fixes #113, related to #120
=> Simplify discovery query, refactor dump-devinfo

.pre-commit-config.yaml, CHANGELOG.md, kasa/smartstrip.py, poetry.lock, pyproject.toml
Most notable changes:
* Devices initialized by discovery are pre-initialized using the discovery response data, so no need for update() directly after discovery
* Only the basic information is requested during discovery, as some HS110 and HS220 devices do not respond to multi-module queries
* Fix mac address parsing for KL430
* Add support for KL125 color temperature ranges
* Documentation updates!
Fixes #138 Fixes #169
=> Prepare 0.4.0.dev3

devtools/dump_devinfo.py
`latitude` and `longitude` values were not handled previously properly like the variants with `_i`, causing an exception when re.sub() scrubbing was called with a float parameter.
* also, -d/--debug is now a flag
=> dump_devinfo: handle latitude/longitude keys properly

kasa/cli.py
**Temperature is not supported on plugs**
One of the best things about this python library is that even when we throw unsupported commands at it, it doesn't return errors because there is a clause to tell the user it isn't supported. To maintain this clean style, a simple `if not dev.is_plug:` can prevent the user from receiving errors if they attempt to change the colour temperature of a plug. This is already set with changing the brightness of a plug so why not here?
Consider this pull request. 
- Thanks
=> cli: add human-friendly printout when calling temperature on non-supported devices

README.md, kasa/cli.py, kasa/smartdevice.py, kasa/smartstrip.py, kasa/tests/conftest.py, kasa/tests/newfakes.py, kasa/tests/test_bulb.py, kasa/tests/test_cli.py, kasa/tests/test_discovery.py, kasa/tests/test_emeter.py, kasa/tests/test_plug.py, kasa/tests/test_smartdevice.py, kasa/tests/test_strip.py, pyproject.toml
* Fix running tests on a real device, tested on hs110, kp303 and kl130.
* Fix some issues on tests spotted while testing against real devices. More fixes to real tests will follow in a separate PR.
* Add a note to README how to run the tests.
=> Improve testing harness to allow tests on real devices

kasa/discover.py
Updated discovery documentation for multiple interfaces explanation
Fixes #167
=> Add a note about using the discovery target parameter

kasa/smartbulb.py, kasa/tests/test_bulb.py
* add ColorTempRange and HSV named tuples
* add a fallback color temp range if unknown, log a warning
* set_hsv: the value is now optional
=> bulb: allow set_hsv without v, add fallback ct range

.github/workflows/ci.yml, CHANGELOG.md, RELEASING.md, pyproject.toml
The most important enhancements in this release are:
* Support for emeter on strip sockets
* Fix discovery and update() on some devices that do not support multi-module queries (e.g., HS200)
* Improved support for bulbs
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.4.0.dev3...0.4.0.dev4)
- HS300 Children plugs have emeter [\#64](https://github.com/python-kasa/python-kasa/issues/64)
- Improve emeterstatus API, move into own module [\#205](https://github.com/python-kasa/python-kasa/pull/205) ([rytilahti](https://github.com/rytilahti))
- Avoid temp array during encrypt and decrypt [\#204](https://github.com/python-kasa/python-kasa/pull/204) ([bdraco](https://github.com/bdraco))
- Add emeter support for strip sockets …
=> Release 0.4.0.dev4

CHANGELOG.md, pyproject.toml
This release introduces re-using the device connection to get rid of (sometimes slow) connection establishment.
This is especially useful for emeter-enabled smart strips or any other usecases requiring consecutive I/O requests.
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.4.0.dev4...0.4.0.dev5)
**Merged pull requests:**
- Add KL130 fixture, initial lightstrip tests [\#214](https://github.com/python-kasa/python-kasa/pull/214) ([rytilahti](https://github.com/rytilahti))
- Keep connection open and lock to prevent duplicate requests [\#213](https://github.com/python-kasa/python-kasa/pull/213) ([bdraco](https://github.com/bdraco))
- Cleanup discovery & add tests [\#212](https://github.com/python-kasa/python-kasa/pull/212) ([rytilahti](https://github.com/rytilahti))
=> Release 0.4.0.dev5

CHANGELOG.md, README.md, RELEASING.md, pyproject.toml
This is the first proper python-kasa release since forking from pyhs100.
* Improved I/O handling, including asyncio interface, request merging & connection sharing
* API improvements throughout the whole package
* Support for LED strips
* Improved bulb support (transitions, support for more models)
* Onboarding is now possible without a mobile app
* Improved documentation
* And various other improvements, see the full changelog for details!
Thanks to all contributors, from testers, and issue reporters to those who have submitted pull requests! Thanks also to those who donated test devices to help to make this release happen!
Special thanks for this release go to @basnijholt (initial asyncio port, push to make this fork happen) and @bdraco (fixing the last release blocker, emeter support …
=> Release 0.4.0

kasa/tests/fixtures/KP400(US)_2.0_1.0.6.json
I think #149 isn't an issue anymore, but I could be wrong.
@dlee1j1 do you still see an issue on the master branch?
```
== TP-LINK_Smart Plug_DC2A - KP400(US) ==
Host: 192.168.107.71
Device state: ON
== Plugs ==
* Socket 'Anc ' state: ON on_since: 2021-10-03 13:54:17.893155
* Socket 'Plug 2' state: ON on_since: 2021-10-03 13:54:17.893235
== Generic information ==
Time:         2021-10-03 14:01:30
Hardware:     2.0
Software:     1.0.6 Build 200821 Rel.090909
MAC (rssi):   40:3F:8C:A8:DC:2A (-46)
Location:     {'latitude': 29.7852, 'longitude': -95.4073}
== Device specific information ==
LED state: True
Childs count: 2
On since: 2021-10-03 13:54:17.904614
```
=> Add fixture for newer KP400 firmware

.github/workflows/publish.yml
The CD pipeline pieces are not currently working properly, this is a stopgap solution to avoid all merges on master to fail due to testpypi upload failure happening always after the first merged PR for the given version.
If testpypi uploads are wanted, https://github.com/pypa/setuptools_scm could be considered to handle the versioning.
=> Allow publish on test pypi workflow to fail

kasa/cli.py, kasa/modules/__init__.py, kasa/modules/antitheft.py, kasa/modules/cloud.py, kasa/modules/countdown.py, kasa/modules/emeter.py, kasa/modules/module.py, kasa/modules/rulemodule.py, kasa/modules/schedule.py, kasa/modules/time.py, kasa/modules/usage.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartplug.py, kasa/smartstrip.py, poetry.lock, pyproject.toml
This PR creates a modularized foundation to expose more features on the supported devices, with the goal of making it more straightforward to implement new features in the future. This PR should not break the API.
At the moment, the most visible change is that each update cycle queries the information from all modules in a single query:
* Basic system info
* Cloud (new)
* Countdown (new)
* Antitheft (new)
* Schedule (new)
* Usage (new)
* Time (existing, implements the time/timezone handling)
* Emeter (existing, partially separated from smartdevice)
As some devices are known to be picky on multimodule queries, I'm marking this a draft in hopes of getting feedback if this works on the majority of devices as it is or not.
Further updates and improvements are to be done on `modularize` branch …
=> Add module support & query their information during update cycle

poetry.lock, pyproject.toml
Looks like some version update done on the doc build PR broke coverage, this makes it build again by adding explicit dependency on coverage[toml].
=> Add coverage[toml] dependency to fix coverage on CI

.github/workflows/ci.yml
The v1 is deprecated and will be removed in the near future, see https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1
=> Use codecov-action@v2 for CI

kasa/cli.py, kasa/tests/test_cli.py
* Supported values: plug, bulb, strip, lightstrip, dimmer
* Deprecate --bulb, --plug, --strip, --lightstrip
I noted that there's no way to control dimmers from the cli while checking out #268, so that offered an opportunity to simplify the code a bit.
=> Add --type option to cli

.github/workflows/publish.yml
* Instead of master commits, create a release when github release gets published
* Remove testpypi uploads
=> Publish to pypi on github release published

CHANGELOG.md, pyproject.toml
This minor release fixes issues that were found after homeassistant integration got converted over from pyhs100.
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.4.0...0.4.1)
- Add --type option to cli [\#269](https://github.com/python-kasa/python-kasa/pull/269) ([rytilahti](https://github.com/rytilahti))
- Minor improvements to onboarding doc [\#264](https://github.com/python-kasa/python-kasa/pull/264) ([rytilahti](https://github.com/rytilahti))
- Add fixture file for KL135 [\#263](https://github.com/python-kasa/python-kasa/pull/263) ([ErikSGross](https://github.com/ErikSGross))
- Add KL135 color temperature range [\#256](https://github.com/python-kasa/python-kasa/pull/256) ([rytilahti](https://github.com/rytilahti))
- Add py.typed to …
=> Prepare 0.4.1

kasa/modules/module.py, kasa/smartdevice.py
We know after the initial update whether a module is supported or not, so no need to request unsupported ones in future update cycles.
=> Do not request unsupported modules after the initial update

kasa/protocol.py
Fixes
```
Exception ignored in: <function TPLinkSmartHomeProtocol.__del__ at 0x1096d0670>
Traceback (most recent call last):
File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/kasa/protocol.py", line 159, in __del__
self.writer.close()
File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 353, in close
return self._transport.close()
File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 700, in close
self._loop.call_soon(self._call_connection_lost, None)
File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 748, in call_soon
self._check_thread()
File …
```
=> Fix unsafe __del__ in TPLinkSmartHomeProtocol

kasa/smartdevice.py
Raise an exception to inform the caller that update() is needed
The emeter information is not available if the device has been initialized from the discovery information, and no update() has been called.
Related to #302
=> Guard emeter accesses to avoid keyerrors

kasa/cli.py
* KASA_TYPE defines the device type (bulb, plug, dimmer, strip, lightstrip)
* KASA_TARGET to define discovery target
* KASA_DEBUG to enable debugging
Related to https://github.com/python-kasa/python-kasa/issues/311#issuecomment-1039496738
=> Allow environment variables for discovery target, device type and debug

kasa/tests/test_cli.py
The tests were taking a long time to run because this wasn't patched out
=> Fix test_deprecated_type stalling

kasa/cli.py, kasa/modules/__init__.py, kasa/modules/ambientlight.py, kasa/modules/antitheft.py, kasa/modules/cloud.py, kasa/modules/countdown.py, kasa/modules/emeter.py, kasa/modules/module.py, kasa/modules/motion.py, kasa/modules/rulemodule.py, kasa/modules/schedule.py, kasa/modules/time.py, kasa/modules/usage.py, kasa/protocol.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartdimmer.py, kasa/smartplug.py, kasa/smartstrip.py, kasa/tests/test_smartdevice.py, poetry.lock, pyproject.toml
This PR creates a modularized foundation to expose more features on the supported devices, making it more straightforward to implement new features in the future. This work forms the basis for 0.5 series.
At the moment, the most visible change is that each update cycle queries the information from all modules supported by the device type in a single query:
* Basic system info
* Cloud (new)
* Countdown (new)
* Antitheft (new)
* Schedule (new)
* Usage (new)
* Time (existing, implements the time/timezone handling)
* Emeter (existing, partially separated from smartdevice))
* Ambientlight (new, for dimmers)
* Motion (new, for dimmers)
Some of the new features are directly exposed to the cli while others are not, the follow-up PRs should add module-based tests and expose features where it makes …
=> Convert the codebase to be more modular

.github_changelog_generator, CHANGELOG.md, RELEASING.md, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.4.3...0.5.0)
This is the first release of 0.5 series which includes converting the code base towards more modular approach where device-exposed modules (e.g., emeter, antitheft, or schedule) are implemented in their separate python modules to decouple them from the device-specific classes.
There should be no API breaking changes, but some previous issues hint that there may be as information from all supported modules are now requested during each update cycle (depending on the device type):
* Basic system info
* Emeter
* Time - properties (like `on_since`) use now time from the device for calculation to avoid jitter caused by different time between the host and the device
* Usage statistics - similar interface to …
=> Prepare 0.5.0

kasa/cli.py, kasa/tests/test_cli.py
Fixes regression reported in #371 where the `get_emeter_monthly` was not called by passing the year value as keyword-only argument.
=> Fix year emeter for cli by using kwarg for year parameter

docs/source/cli.rst, docs/source/design.rst, docs/source/discover.rst, docs/source/smartbulb.rst, docs/source/smartdevice.rst, docs/source/smartdimmer.rst, docs/source/smartlightstrip.rst, docs/source/smartplug.rst, docs/source/smartstrip.rst
This makes it easier to get an overview of the documentation and link to specific sections directly from the top of the page.
=> Add ToCs for doc pages

README.md, docs/source/cli.rst, docs/source/smartbulb.rst
All documentation tweaks.
All command examples were tested with current release:
```text
hbarta@pilog3b:~/Downloads/byte-unixbench/UnixBench$ kasa --version
kasa, version 0.5.0
hbarta@pilog3b:~/Downloads/byte-unixbench/UnixBench$ 
```
One command failed (and with multiple stacks to unwind :o ) 
```text
kasa --type bulb --host <host> hsv 0 100 20 --transition 15000
```
I believe the syntax is correct and there may be a problem with the code, but that is a subject for another issue.
=> fix more outdated CLI examples, remove EP40 from bulb list

docs/source/smartstrip.rst
```text
hbarta@pilog3b:~$ kasa --type strip --host 192.168.20.215 on
Turning on TP-LINK_Smart Plug_83A6
hbarta@pilog3b:~$ kasa --strip --host 192.168.20.215 on
Usage: kasa [OPTIONS] COMMAND [ARGS]...
Try 'kasa --help' for help.
Error: No such option: --strip (Possible options: --host, --type)
hbarta@pilog3b:~$
```
=> Fix outdated smartstrip cli examples

docs/source/smartbulb.rst, kasa/__init__.py, kasa/cli.py, kasa/smartbulb.py, kasa/tests/newfakes.py, kasa/tests/test_bulb.py
This PR adds support for listing and modifying the presets on bulbs.
`SmartBulb` API is extended by one new property (`presets`) to return a list of current presets, and by one new method (`save_preset(SmartBulbPreset)`) to modify an existing one.
The CLI tool can be used to list and modify the presets.
```
kasa presets --help
Usage: kasa presets [OPTIONS] COMMAND [ARGS]...
List and modify bulb setting presets.
Options:
--help  Show this message and exit.
Commands:
list    List presets.
modify  Modify a preset.
```
To modify a preset, you can pass any options that should be modified for the given preset:
```
kasa presets modify --help
Usage: kasa presets modify [OPTIONS] INDEX
Modify a preset.
Options:
--brightness INTEGER
--hue INTEGER
--saturation INTEGER
--temperature INTEGER
--help …
```
=> Add support for bulb presets

kasa/cli.py
click.Choice argument is type hinted as a Sequence convert TYPE_TO_CLASS to a list of its keys to pass it in.
Fixes pylance warning (fixes #384)
=> Fix type hinting issue with call to click.Choice 

kasa/cli.py
I was looking for a quick way to delete schedules via cli now that the official Kasa app is requiring an account. Discovered this was already implemented in this library but not yet in the cli.
=> Adding cli command to delete a schedule rule

kasa/smartbulb.py
At least some of the light strips do not support transitions, this PR documents this behavior.
Reported at #389
=> Add a note that transition is not supported by all devices

kasa/tests/conftest.py, kasa/tests/test_bulb.py, kasa/tests/test_cli.py, kasa/tests/test_dimmer.py, kasa/tests/test_discovery.py, kasa/tests/test_emeter.py, kasa/tests/test_lightstrip.py, kasa/tests/test_plug.py, kasa/tests/test_protocol.py, kasa/tests/test_smartdevice.py, kasa/tests/test_strip.py, pyproject.toml
As mentioned in https://github.com/python-kasa/python-kasa/issues/396
Solution is to turn on auto mode in the pytest section of the toml file, and then remove the global async marking flag.
lib\site-packages\pytest_asyncio\plugin.py:191
C:\Users\jphda\miniconda3\envs\python-kasa\lib\site-packages\pytest_asyncio\plugin.py:191: DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)
lib\site-packages\pytest_asyncio\plugin.py:230
C:\Users\jphda\miniconda3\envs\python-kasa\lib\site-packages\pytest_asyncio\plugin.py:230: DeprecationWarning: '@pytest.fixture' is applied to <fixture dev, …
=> Fix pytest warnings about asyncio

.pre-commit-config.yaml
Flake8 has moved to github, this fixes the build.
=> Update pre-commit url for flake8

kasa/smartlightstrip.py, kasa/tests/test_lightstrip.py
This allows for defining the wanted brightness directly when setting an effect by its name.
Untested as I don't have a test device, feel free to test if you have one.
Slightly related to fixing https://github.com/home-assistant/core/issues/84671 properly.
=> Add brightness to lightstrip's set_effect

.gitattributes
Added .gitattributes file to retain LF only EOL markers when checking out on Windows to prevent excessive warnings from doc8 when doing pre-commit
Windows defaults to CRLF most of the time and when you check out LF only files typically get converted and then restored when committed. As doc8 does checks during pre-commit on rst files its handy to have them default to not being converted when pulled.
=> Added .gitattributes file to retain LF only EOL markers when checking out on Windows

kasa/cli.py
Print out the repr of captured exception instead of full traceback
Fixes #425
=> Pretty-print all exceptions from cli commands

kasa/smartlightstrip.py, kasa/tests/test_lightstrip.py
This adds a transition parameter to `set_effect`, which has not been tested on a real device and might change in the future.
~Marking this as draft as I'm not sure if the transition parameter behaves similarly as for bulbs (considering some effects have a also separate `transition_range`).~
=> Add transition parameter to lightstrip's set_effect

kasa/modules/emeter.py, kasa/modules/usage.py, kasa/smartdevice.py, kasa/tests/test_usage.py
This is an initial fix for the issue discussed here:
Fixes https://github.com/python-kasa/python-kasa/issues/373
This code largely duplicates the solution used for the Emeter module.
I have work in progress on a pydantic based version for which I will create a second PR.
=> Return usage.get_{monthstat,daystat} in expected format 

kasa/cli.py, kasa/tests/test_cli.py
Passing --json will now suppress the standard output and provides JSON output,
which is command-dependent:
* Commands that act directly on the device will return the raw device response as-is.
* Commands that return just a parsed format of some specific information (like `time`) will return just that information.
The likely most useful usecase is just dumping the whole device state for further processing, which can be done by using using `kasa --json --host 192.168.xx.xx state`:
```
❯ kasa --json --host 192.168.250.188 state|jq 'map_values(keys)'
{
"system": [
"get_sysinfo"
],
"schedule": [
"get_daystat",
"get_monthstat",
"get_next_action",
"get_realtime",
"get_rules"
],
"anti_theft": [
"get_next_action",
"get_rules"
],
"time": [
"get_time",
"get_timezone"
],
"cnCloud": [
"get_info"
], …
```
=> Add support for json output

kasa/smartbulb.py, kasa/tests/test_bulb.py
The payloads differ on light strips depending on whether the preset is for an effect or for regular bulb settings.
Fixes #439
=> Allow effect presets seen on light strips

.github/workflows/ci.yml, .pre-commit-config.yaml, .readthedocs.yml, kasa/tests/test_cli.py, kasa/tests/test_discovery.py, kasa/tests/test_protocol.py, kasa/tests/test_readme_examples.py, pyproject.toml
Python 3.7 will become EOL by the end of June '23, so I think we can drop its support whenever a new release gets done.
=> Drop python 3.7 support

kasa/modules/motion.py
This allows obtaining and changing the inactivity timeout for motion detectors.
Per comment in #452, there is a default rule that reverts this back to 60s which needs to be deleted if you want to use this.
Closes #452
=> Add inactivity setting for the motion module

kasa/__init__.py, poetry.lock, pyproject.toml
This is no longer needed, as python 3.8 has native importlib.metadata
=> Remove importlib-metadata dependency

CHANGELOG.md, pyproject.toml
Besides some small improvements, this release:
* Adds optional dependency for for `orjson` and `kasa-crypt` to speed-up protocol handling by an order of magnitude.
* Drops Python 3.7 support as it is no longer maintained.
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.5.1...0.5.2)
=> Release 0.5.2

kasa/cli.py, kasa/discover.py, kasa/protocol.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartdimmer.py, kasa/smartlightstrip.py, kasa/smartplug.py, kasa/smartstrip.py, kasa/tests/test_discovery.py, kasa/tests/test_protocol.py
My use case is very similar to the discussion https://github.com/python-kasa/python-kasa/discussions/410.
I have an internal network with IoT devices. The network is separated from my home network, so rouge IoT devices don't have the ability to hack my PCs (that happened once).  I only expose ports that IoT devices need. Since I have multiple tp-link kasa devices, I need to do port forwarding to different ports.
=> Make device port configurable

kasa/protocol.py, poetry.lock, pyproject.toml
Note: CI failure is fixed by https://github.com/python-kasa/python-kasa/pull/482
`asyncio.wait_for` has some underlying problems that are only fixed in cpython 3.12. 
Use `async_timeout` instead until the minimum supported version is 3.11+ and it can be replaced with `asyncio.timeout` 
See https://github.com/python/cpython/pull/98518
=> Replace asyncio.wait_for with async-timeout

CHANGELOG.md, pyproject.toml
This release adds support for defining the device port and introduces dependency on async-timeout which improves timeout handling.
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.5.2...0.5.3)
=> Release 0.5.3

devtools/README.md, devtools/create_module_fixtures.py
I created this script earlier to test the idea of having module-specific fixture files for testing, but never had time to finish working on that. This draft is created just to not forget about it completely.
```
Usage: create_module_fixtures.py [OPTIONS] OUTPUTDIR
Create module fixtures for given host/network.
Arguments:
OUTPUTDIR  [required]
Options:
--host TEXT
--network TEXT
--install-completion  Install completion for the current shell.
--show-completion     Show completion for the current shell, to copy it or
customize the installation.
--help                Show this message and exit.
```
for example:
```
python create_module_fixtures.py --network 192.168.4.255 /tmp/testfix
```
will create files from the given network under `/tmp/testfix/`:
```
ls -alR /tmp/testfix/
❯ ls -alR …
```
=> Add devtools script to create module fixtures

kasa/modules/cloud.py, kasa/modules/rulemodule.py, kasa/smartbulb.py, poetry.lock, pyproject.toml
This makes python-kasa compatile with both pydantic v1 and pydantic v2.
Related to https://github.com/home-assistant/core/issues/99218 - Fixes #491
=> Add support for pydantic v2 using v1 shims

kasa/cli.py, kasa/discover.py, kasa/exceptions.py, kasa/tests/test_discovery.py
This PR will broadcast the new discovery message on the new port and log any responses received as unsupported devices.
=> Add support for alternative discovery protocol (20002/udp)

kasa/cli.py, kasa/tests/test_cli.py
Display an error if both --alias and --host are defined to avoid ambiguous target device:
```
❯ kasa --host 123 --alias 123 state
Usage: kasa [OPTIONS] COMMAND [ARGS]...
Try 'kasa --help' for help.
Error: Use either --alias or --host, not both.
```
Also, use `click.BadOptionUsage` consistently for other errors, like when only `--username` or `--password` is given.
Related to #511
=> Show an error if both --alias and --host are defined

kasa/smartdevice.py, kasa/smartstrip.py, kasa/tests/test_smartdevice.py
Every time emeter functions were called features had to be re-parsed.  For power strips, thats a lot of re-parses. Only parse them when we update
=> Parse features only during updates

kasa/discover.py, kasa/tests/test_discovery.py
This should equate to a significant reliability improvement for networks with poor wifi (edge of range)/udp.
needs https://github.com/python-kasa/python-kasa/pull/494
related issue https://github.com/home-assistant/core/issues/99449
Can be tested with HA by doing
```diff
diff --git a/homeassistant/components/tplink/__init__.py b/homeassistant/components/tplink/__init__.py
index d8285cbed70..1c98c1e1ae1 100644
--- a/homeassistant/components/tplink/__init__.py
+++ b/homeassistant/components/tplink/__init__.py
@@ -87,7 +87,7 @@ async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
"""Set up TPLink from a config entry."""
host = entry.data[CONF_HOST]
try:
-        device: SmartDevice = await Discover.discover_single(host)
+        device: SmartDevice = await …
```
=> Add a connect_single method to Discover to avoid the need for UDP

kasa/smartstrip.py
The `on_since` for smarstrip child sockets was implemented completely wrong, so apparently no one ever used it.
This fixes it to follow the same pattern as the main device, i.e., giving out a datetime object (based on local time, no timezone handling) since it's been on.
=> Fix on_since for smartstrip sockets

.github/workflows/publish.yml
See https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/ and https://docs.pypi.org/trusted-publishers/using-a-publisher/
=> Use trusted publisher for publishing to pypi

.flake8, .github/workflows/ci.yml, .pre-commit-config.yaml, devtools/check_readme_vs_fixtures.py, devtools/dump_devinfo.py, devtools/parse_pcap.py, devtools/perftest.py, kasa/cli.py, kasa/discover.py, kasa/emeterstatus.py, kasa/modules/emeter.py, kasa/modules/module.py, kasa/modules/usage.py, kasa/protocol.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartdimmer.py, kasa/smartlightstrip.py, kasa/smartplug.py, kasa/smartstrip.py, kasa/tests/newfakes.py, kasa/tests/test_cli.py, kasa/tests/test_discovery.py, kasa/tests/test_smartdevice.py, pyproject.toml, tox.ini
This converts the code base to use ruff for both linting and code formatting, allowing to speed-up the CI and simplify the setup.
This drops the dependency for the following tools:
* black
* isort
* pyupgrade
* flake8
and fixes all reported issues.
=> Use ruff and ruff format

.github/workflows/ci.yml
Adds python 3.12 and pypy-3.10 to CI.
We test currently for all supported cpython versions, and the oldest and the latest pypy versions.
Also, cleanup the action file a bit:
* Update action versions
* Remove commented out yaml
* Disable fail_ci_if_error for codecov
=> Add python3.12 and pypy-3.10 to CI

kasa/discover.py, kasa/tests/test_discovery.py
While looking at merged PR https://github.com/python-kasa/python-kasa/pull/528 I noticed some users were using hostnames to add their devices and the current discover_single will not work with hostnames.  This PR does a simple DNS lookup using getaddrinfo if a hostname is used so that it can match to the datagram response ip.
According to the [getaddrinfo docs](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html) dns lookup only happens if node parameter is a hostname:
> node specifies either a
>        numerical network address (for IPv4, numbers-and-dots notation as
>        supported by [inet_aton(3)](https://man7.org/linux/man-pages/man3/inet_aton.3.html); for IPv6, hexadecimal string format as
>        supported by [inet_pton(3)](https://man7.org/linux/man-pages/man3/inet_pton.3. …
=> Update discover single to handle hostnames

kasa/discover.py, kasa/smartdevice.py, kasa/tests/newfakes.py, kasa/tests/test_discovery.py, kasa/tests/test_smartdevice.py
This change removes the `device.update()` call in discover_single so that the logic is consistent with `discover()` which only uses UDP and relies solely on `device.update_from_discover_info()`.  Reasons are:
1. CLI does `device.update()` anyway so it's a duplicate call there.
2. Consistent with approach in [Add klap protocol PR](https://github.com/python-kasa/python-kasa/pull/509) which removed unnecessary `device.update()` calls.
3. Separation of discovery UDP protocol from device `device.update()` should make downstream issues clearer.
EDIT:
This change inadvertently reduced test coverage because by a fluke `test_discover_single()` was hitting the following path in smartdevice.py L348 when the fixture specified it didn't support emeter:
```
if not module.is_supported: …
```
=> Do not do update() in discover_single

devtools/dump_devinfo.py, kasa/tapo/__init__.py, kasa/tapo/tapodevice.py
We need to be careful not merge any of these new fixtures without the test framework changes in https://github.com/python-kasa/python-kasa/pull/557 or they will break the tests.
=> Update dump_devinfo to produce new TAPO/SMART fixtures

kasa/cli.py
* `KASA_JSON` allows now forcing json output, `--no-json` is added to the flag to revert this for an invocation.
* `TPLINK_CLOUD_{USERNAME,PASSWORD}` are renamed to `KASA_{USERNAME,PASSWORD}` to follow the naming scheme used by rest of the options.
=> Use consistent naming for cli envvars

README.md
All in all, making the readme more approachable landing page:
* Link to provisioning docs from the beginning
* Hints about support for tapo devices
* Add some documentation about how to pass credentials
* Clearer usage instructions and links to find more information
=> Update readme with clearer instructions, tapo support

kasa/aestransport.py, kasa/smartprotocol.py
Log raw smartprotocol requests to help debugging invalid queries.
Also, comment out the encrypted secure_passthrough response for the time being to avoid too much output. We might want to hide low-level protocol debug messages behind a separate debug level or something, as most of that may not be that useful?
@sdb9696, opinions on this?
=> Log smartprotocol requests

kasa/cli.py, kasa/discover.py, kasa/exceptions.py, kasa/tests/conftest.py, kasa/tests/newfakes.py, kasa/tests/test_cli.py, kasa/tests/test_discovery.py
- Show discovery results for unsupported devices and devices that fail to authenticate.
- Rename `--show-unsupported` to `--verbose`.
- Remove separate `--timeout` parameter from cli discovery so it's not confused with `--timeout` now [added to cli command](https://github.com/python-kasa/python-kasa/commit/347cbfe3bdaa4c492ef74508bbe47bdfdc49e587)
- Add tests.
=> Improve CLI Discovery output

kasa/aestransport.py, kasa/device_factory.py, kasa/iotprotocol.py, kasa/klaptransport.py, kasa/protocol.py, kasa/smartdevice.py, kasa/smartprotocol.py, kasa/tapo/tapodevice.py, kasa/tests/newfakes.py, kasa/tests/test_aestransport.py, kasa/tests/test_klapprotocol.py, kasa/tests/test_protocol.py, kasa/tests/test_smartdevice.py
Removes the `login` and `handshake` from the protocol class and does it entirely within the transport.
Also includes tests for aestransport and refactoring of the `__init__` signatures
=> Do login entirely within AesTransport

kasa/aestransport.py, kasa/exceptions.py, kasa/iotprotocol.py, kasa/smartprotocol.py, kasa/tapo/tapodevice.py, kasa/tapo/tapoplug.py, kasa/tests/conftest.py, kasa/tests/newfakes.py, kasa/tests/test_aestransport.py, kasa/tests/test_emeter.py, kasa/tests/test_klapprotocol.py, kasa/tests/test_smartdevice.py, kasa/tests/test_smartprotocol.py
Hopefully a nice and small PR to enable `multipleRequest` in `smartprotocol` and the test framework.
A subsequent PRs will introduce the smart request helper functions and use the `component_nego` result to determine which requests to make rather than hardcoding.
=> Enable multiple requests in smartprotocol

kasa/cli.py, kasa/tests/test_cli.py
* `--verbose` is not anymore specific to discover command
* `-v` shortcut can be used to activate it, similarly as `-d` works for `--debug`
=> Elevate --verbose to top-level option

kasa/tapo/tapobulb.py, kasa/tapo/tapodevice.py, kasa/tapo/tapoplug.py, kasa/tests/test_smartdevice.py
This will also use the existence of energy_monitoring in the component_nego query to decide if the device has the service, making it accessible for non-plug devices which may have the feature.
The way how extra requests based on available components are handled requires some thinking, but I suppose this is better than what we had.
=> Pull up emeter handling to tapodevice base class

kasa/cli.py, kasa/smartdevice.py, kasa/tapo/tapodevice.py
Implement `wifi_scan` and `wifi_join` for SMART devices, allows to change the wifi settings using the cli.
This maybe helpful for #565 if some of those known hardcoded creds work for non-provisioned setups.
Tested to work on P110.
=> Implement wifi interface for tapodevice

kasa/aestransport.py, kasa/cli.py, kasa/deviceconfig.py, kasa/discover.py, kasa/klaptransport.py, kasa/protocol.py, kasa/smartdevice.py, kasa/tapo/tapodevice.py, kasa/tests/conftest.py, kasa/tests/newfakes.py, kasa/tests/test_deviceconfig.py, kasa/tests/test_discovery.py, kasa/tests/test_protocol.py
As per [HA PR discussion](https://github.com/home-assistant/core/pull/105143#discussion_r1439889873) this PR enables the retrieval of the credentials hash and passing back into the `DeviceConfig`.  This will allow devices to persist all of their config without storing clear text credentials for later retrieval and re-use.
=> Allow serializing and passing of credentials_hashes in DeviceConfig

CHANGELOG.md, pyproject.toml
More proper release notes will be written for the final release, this release is done to make it easier to test changes on homeassistant & co.
The release blockers can be followed in the 0.6.0 milestone: https://github.com/python-kasa/python-kasa/milestone/7
=> Release 0.6.0.dev0

pyproject.toml
Otherwise, the file would be extracted into the main site-packages which is rather unexpected..
```
Uninstalling python-kasa-0.6.0.dev0:
Would remove:
/home/tpr/.virtualenvs/default/bin/kasa
/home/tpr/.virtualenvs/default/lib/python3.11/site-packages/CHANGELOG.md
/home/tpr/.virtualenvs/default/lib/python3.11/site-packages/kasa/*
/home/tpr/.virtualenvs/default/lib/python3.11/site-packages/python_kasa-0.6.0.dev0.dist-info/*
Proceed (Y/n)?
```
=> Ship CHANGELOG only in sdist

kasa/aestransport.py, kasa/cli.py, kasa/klaptransport.py
https://github.com/python-kasa/python-kasa/pull/607 introduced a bug when calling `kasa` without any `--username` and `--password` for devices requiring authentication.  This PR fixes the bug and ensures that `Credentials` created with `None` values will be replaced with empty string credentials.
=> Fix cli discover bug with None username/password

kasa/tapo/tapobulb.py
L900 reports a color temperature range as [9000, 9000] so this changes the way we check for color temperature support.
=> Check the ct range for color temp support

kasa/modules/emeter.py, kasa/modules/usage.py, kasa/tests/test_emeter.py, kasa/tests/test_usage.py
Most of the time the data we want is at the end of the list so we now search backwards to avoid having to scale all the data and throw most of it away.
The longer the device is on and the later it is in the month, the slower the code would get.
=> Avoid linear search for emeter realtime and emeter_today

kasa/cli.py, kasa/tapo/tapodevice.py
This allows changing the credentials stored in the device, e.g., after provisioning the device. In my personal tests on L900, this changed the credentials from the provisioning creds to my own just fine while still returning a json decode error as response. Maybe some mandatory elements are missing there, but this might still be useful for someone.
As the side effects besides breaking connectivity using previous credentials are unknown, the cli will prompt for confirmation before proceeding.
=> Add update-credentials command

kasa/cli.py, kasa/device_factory.py, kasa/tests/test_cli.py
Support getting child plug emeter status from power strips such as the HS300 via the CLI.
Fixes https://github.com/python-kasa/python-kasa/issues/462
=> Get child emeters with CLI

kasa/deviceconfig.py, kasa/tests/test_deviceconfig.py
This change will ensure that if an empty string is passed in as the `credential_hash` to `to_dict()` (i.e. the hash from the legacy protocol) that the resulting dict will exclude both the `credentials` and the `credentials_hash`.  This is needed for HA so it doesn't need to be aware of whether to persist the credentials or not and will avoid it saving the cached plain text credentials for legacy devices.
=> Update config to_dict to exclude credentials if the hash is empty string

kasa/__init__.py, kasa/discover.py
This is to allow consumers (i.e. HA) to handle and try to `SmartDevice.connect()` for legacy.  Raising `SmartDeviceException` is too broad as consumers could try to connect to unsupported devices etc.
=> Raise TimeoutException on discover_single timeout

kasa/protocol.py, kasa/tests/test_protocol.py
If the task the query is running in it cancelled, we do know the state of the connection so we must close. Previously we would not close on BaseException which could result in reading the previous response if the previous query was cancelled after the request had been sent
aiohttp cancels tasks when the connection drops so its possible for the task that the query is running in to get cancelled 
related issue https://github.com/home-assistant/core/issues/107202
=> Fix connection indeterminate state on cancellation

poetry.lock, pyproject.toml
Seems to be because the latest `sphinxcontrib-applehelp` version requires `sphinx>=5.0".
Builds [started failing](https://readthedocs.org/projects/python-kasa/builds/) after Jan 13th when the latest `sphinxcontrib-applehelp` was [released](https://pypi.org/project/sphinxcontrib-applehelp/#history)
=> Fix broken docs due to applehelp dependency

devtools/helpers/smartrequests.py, kasa/aestransport.py, kasa/deviceconfig.py, kasa/exceptions.py, kasa/httpclient.py, kasa/httpclientsession.py, kasa/iotprotocol.py, kasa/klaptransport.py, kasa/smartprotocol.py, kasa/tests/test_device_factory.py, kasa/tests/test_discovery.py, kasa/tests/test_klapprotocol.py
Allows for easier migration between async `http` implementations and makes retry logic more consistent between protocols.
=> Encapsulate http client dependency

CHANGELOG.md, RELEASING.md, pyproject.toml
This major brings major changes to the library by adding support for devices that require authentication for communications, all of this being possible thanks to the great work by @sdb9696!
This release adds support to a large range of previously unsupported devices, including:
* Newer kasa-branded devices, including Matter-enabled devices like KP125M
* Newer hardware/firmware versions on some models, like EP25, that suddenly changed the used protocol
* Tapo-branded devices like plugs (P110), light bulbs (KL530), LED strips (L900, L920), and wall switches (KS205, KS225)
* UK variant of HS110, which was the first device using the new protocol
If your device that is not currently listed as supported is working, please consider contributing a test fixture file.
Special thanks goes to …
=> Release 0.6.0

kasa/exceptions.py, kasa/httpclient.py, kasa/tests/test_httpclient.py
- aiohttp `read` moved inside the try block
- Exceptions from http client will show the causing exception
- TimeoutException also inherits from `asyncio.TimeoutError` which will allow it to be caught by HA update_coordinator for better logging.
=> Fix httpclient exceptions on read and improve error info

kasa/aestransport.py, kasa/iotprotocol.py, kasa/smartprotocol.py, kasa/tests/test_klapprotocol.py
- Call close on each try for `ConnectionException` and `RetryableException` in `SmartProtocol` consistent with `TimeoutException`.
- Update `IotProtocol` and `AesTransport` to match the changes above and those made by https://github.com/python-kasa/python-kasa/pull/654 (including docstrings)
=> Make close behaviour consistent across new protocols and transports

devtools/README.md, devtools/dump_devinfo.py, kasa/smartdevice.py, kasa/tests/fixtures/HS110(EU)_1.0_1.2.5.json, kasa/tests/fixtures/HS110(EU)_4.0_1.0.4.json, kasa/tests/fixtures/KL130(EU)_1.0_1.8.8.json, kasa/tests/fixtures/KP115(EU)_1.0_1.0.16.json, kasa/tests/fixtures/KP303(UK)_1.0_1.0.3.json, kasa/tests/fixtures/smart/L530E(EU)_3.0_1.0.6.json, kasa/tests/fixtures/smart/L900-5(EU)_1.0_1.0.17.json, kasa/tests/fixtures/smart/P110(EU)_1.0_1.2.3.json
* Scrub only the last three bytes for mac addresses
* Add --target to allow creating fixtures based on discovery
* Save fixtures directly to correct location, add --basedir to allow defining the location of repository root
* Add --autosave to disable prompting for saving
* Update fixtures for devices I have, including one that I had forgotten to add
Closes #652
=> dump_devinfo improvements

kasa/tests/fixtures/smart/L900-5(EU)_1.0_1.1.0.json
* Adds new localSmart module
* Changed from AES to klap
* Doesn't reboot itself when receiving a RST for the cloud connectivity requests
=> Add l900-5 1.1.0 fixture

kasa/discover.py, kasa/tests/test_discovery.py
This will allow devices time to wake up and might improve discovery on congested networks by spacing out the packets.
Fixes #229
=> Sleep between discovery packets

kasa/cli.py
Show the discovery data when passing `--verbose` for `state` command.
Also, clean up the output strings a bit.
=> Show discovery data for state with verbose

kasa/aestransport.py, kasa/httpclient.py, kasa/json.py, kasa/tests/test_aestransport.py
To prevent the KeyPair being generated repeatedly for offline devices.
Fixes https://github.com/python-kasa/python-kasa/issues/675
=> Generate AES KeyPair lazily

kasa/cli.py, kasa/tests/test_cli.py
This makes it possible to perform provisioning & test commands on devices that haven't been provisioned or have otherwise incorrect time.
=> Allow raw-command and wifi without update

kasa/cli.py, kasa/modules/emeter.py
Add new 'command' for arbitrary command execution, as SMART devices do not use modules for raw calls.
The 'raw-command' is now deprecated but remains working for the time being, while using 'command --module <module>' is the recommended way to make raw calls on legacy devices.
=> Add new cli command 'command' to execute arbitrary commands

kasa/tests/test_klapprotocol.py
Reduces `test_klapprotocol` from 75 seconds to 1.5.
=> Fix test_klapprotocol test duration

README.md, devtools/check_readme_vs_fixtures.py
Makes the matcher more strict to avoid false positives (KP123 v. P123)
=> Update readme fixture checker and readme

kasa/tapo/tapodevice.py
If 'has_set_location_info' is false, the geolocation is missing, which causes cli's 'state' to crash.
```
File "/home/tpr/code/python-kasa/kasa/cli.py", line 538, in state
echo(f"\tLocation:     {dev.location}")
^^^^^^^^^^^^
File "/home/tpr/code/python-kasa/kasa/tapo/tapodevice.py", line 150, in location
"latitude": cast(float, self._info.get("latitude")) / 10_000,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```
=> Do not crash on missing geolocation

kasa/cli.py
https://github.com/python-kasa/python-kasa/pull/680 and https://github.com/python-kasa/python-kasa/pull/694 were failing because this was consuming part of the payload
=> Fix overly greedy _strip_rich_formatting

CHANGELOG.md, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.6.0.1...0.6.1)
Release highlights:
* Support for tapo wall switches
* Support for unprovisioned devices
* Performance and stability improvements
- Add support for tapo wall switches \(S500D\) [\#704](https://github.com/python-kasa/python-kasa/pull/704) (@bdraco)
- Add new cli command 'command' to execute arbitrary commands [\#692](https://github.com/python-kasa/python-kasa/pull/692) (@rytilahti)
- Allow raw-command and wifi without update [\#688](https://github.com/python-kasa/python-kasa/pull/688) (@rytilahti)
- Generate AES KeyPair lazily [\#687](https://github.com/python-kasa/python-kasa/pull/687) (@sdb9696)
- Add reboot and factory\_reset to tapodevice …
=> Prepare 0.6.1

kasa/protocol.py, kasa/tests/test_protocol.py, kasa/xortransport.py
This PR adds a concrete `XorTransport` implementation and runs it through all the `test_protocol` tests at the same time as `TPlinkSmartHomeProtocol`.
A subsequent PR will do the switch but for now this is relatively easy to review as it's a completely new file mostly exactly the same as `TPlinkSmartHomeProtocol` but with the retry logic removed and `query` renamed `send` etc.  The test changes are fairly straightforward to parameterise the protocols and transports.
This should be safe to merge into 0.6.1 once approved as there's no change to existing logic.
=> Add concrete XorTransport class with full implementation

devtools/parse_pcap.py, docs/source/design.rst, kasa/__init__.py, kasa/device_factory.py, kasa/discover.py, kasa/iotprotocol.py, kasa/protocol.py, kasa/smartdevice.py, kasa/tests/conftest.py, kasa/tests/newfakes.py, kasa/tests/test_cli.py, kasa/tests/test_device_factory.py, kasa/tests/test_discovery.py, kasa/tests/test_protocol.py, kasa/xortransport.py
Removes duplication and marks `TPLinkSmartHomeProtocol` with a deprecation warning.
Deprecation done in accordance with https://peps.python.org/pep-0562/
=> Switch from TPLinkSmartHomeProtocol to IotProtocol/XorTransport

kasa/klaptransport.py
The standard lib hashlib is faster than `digest = hashes.Hash(hashes.SHA256())`
=> Use hashlib for klap

kasa/deviceconfig.py, kasa/smartprotocol.py, kasa/tests/fixtures/smart/L510E(US)_3.0_1.0.5.json, kasa/tests/test_smartprotocol.py, pyproject.toml
`dumpdev_info` revealed that `multipleRequests` can cause timeouts if they're too large.  This PR introduces a batch size of 5 which currently is not exceeded in the api but will be in the future.
=> Enable batching of multiple requests

kasa/aestransport.py, kasa/exceptions.py, kasa/httpclient.py, kasa/klaptransport.py, kasa/tests/test_aestransport.py, kasa/tests/test_httpclient.py, kasa/tests/test_klapprotocol.py
URLs with IP addresses are expensive to rebuild because an ip_address object has to be created each time. We don't need to rebuild them over and over
=> Avoid rebuilding urls for every request

README.md, kasa/tapo/__init__.py, kasa/tapo/childdevice.py, kasa/tests/conftest.py, kasa/tests/fixtures/smart/P300(EU)_1.0_1.0.13.json, kasa/tests/fixtures/smart/P300(EU)_1.0_1.0.7.json, kasa/tests/newfakes.py, kasa/tests/test_discovery.py, kasa/tests/test_smartprotocol.py
This adds p300 fixtures and marks it as supported.
This also implements a very basic `control_child` for `FakeSmartTransport`.
The device did not allow fixture creation using multirequest.
=> Add P300 fixture

kasa/tests/conftest.py, kasa/tests/test_aestransport.py, kasa/tests/test_bulb.py, kasa/tests/test_childdevice.py, kasa/tests/test_cli.py, kasa/tests/test_device_factory.py, kasa/tests/test_deviceconfig.py, kasa/tests/test_discovery.py, kasa/tests/test_emeter.py, kasa/tests/test_klapprotocol.py, kasa/tests/test_protocol.py, kasa/tests/test_readme_examples.py, kasa/tests/test_smartprotocol.py, kasa/tests/test_usage.py, pyproject.toml
Re-enables https://docs.astral.sh/ruff/rules/unused-import/ for tests to clean up unused imports.
=> Unignore F401 for tests

CHANGELOG.md, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.6.2...0.6.2.1)
- Avoid crashing on childdevice property accesses [\#732](https://github.com/python-kasa/python-kasa/pull/732) (@rytilahti)
**Merged pull requests:**
- Retain last two chars for children device\_id [\#733](https://github.com/python-kasa/python-kasa/pull/733) (@rytilahti)
- Add TP15 fixture [\#730](https://github.com/python-kasa/python-kasa/pull/730) (@bdraco)
- Add TP25 fixtures [\#729](https://github.com/python-kasa/python-kasa/pull/729) (@bdraco)
- Various test code cleanups [\#725](https://github.com/python-kasa/python-kasa/pull/725) (@rytilahti)
- Unignore F401 for tests [\#724](https://github.com/python-kasa/python-kasa/pull/724) (@rytilahti)
=> Prepare 0.6.2.1

kasa/aestransport.py, kasa/cli.py, kasa/httpclient.py, kasa/klaptransport.py, kasa/tests/test_aestransport.py, kasa/tests/test_klapprotocol.py
Makes it possible to use custom ports, needs tests.
=> Fix port-override for aes&klap transports

kasa/cli.py
If the discovery is skipped, there's no discovery information to print.
=> Do not crash cli on missing discovery info

kasa/cli.py, kasa/tests/test_cli.py, pyproject.toml
This makes it easy to get an initialized device instance in a repl to help development and browsing the API.
Depends on ptpython, unsure if it's worth marking it even as an optional dependency, given this is mostly useful for development purposes.
=> Add 'shell' command to cli

kasa/cli.py, kasa/device_factory.py, kasa/tests/test_device_factory.py
To prevent errors being reported by the cli
```
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8ebdd810>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f8eb998d0>, 1199903.275549099)]']
```
=> Ensure connections are closed when cli is finished

kasa/__init__.py, kasa/cli.py, kasa/descriptors.py, kasa/device.py, kasa/feature.py, kasa/iot/iotdevice.py, kasa/iot/iotplug.py, kasa/iot/modules/cloud.py, kasa/iot/modules/module.py, kasa/smart/smartdevice.py, kasa/tests/test_cli.py, kasa/tests/test_feature.py, kasa/tests/test_smartdevice.py
`Device.features()` does not return a set of strings but a mapping (`Dict[str, Feature]`).
The earlier behavior can be implemented by using `set(dev.sys_info["feature"].split(":"))`.
---
This adds a generic interface for all device classes to introspect available device features,
that is necessary to make it easier to support a wide variety of supported devices with different set of features.
This will allow constructing generic interfaces (e.g., in homeassistant) that fetch and change these features without hard-coding the API calls.
`Device.features()` now returns a mapping of `<identifier, Feature>` where the `Feature` contains all necessary information (like the name, the icon, a way to get and change the setting) to present and change the defined feature through its interface.
TBD: …
=> Add generic interface for accessing device features

kasa/exceptions.py, kasa/smart/smartdevice.py, kasa/smartprotocol.py, kasa/tests/test_smartdevice.py, kasa/tests/test_smartprotocol.py
Handle errors within multipleRequests more robustly by not raising every time and passing the error back to the device to handle.
=> Let caller handle SMART errors on multi-requests

devtools/dump_devinfo.py
"la" and "lo" are used in the child dev statuses for geoloc.
=> Fix dump_devinfo scrubbing for ks240

kasa/smart/modules/__init__.py, kasa/smart/modules/ledmodule.py, kasa/smart/smartdevice.py, kasa/tests/fakeprotocol_smart.py
Allows controlling LED on devices that support it.
=> Add smartdevice module for led controls

kasa/feature.py, kasa/smart/modules/__init__.py, kasa/smart/modules/autooffmodule.py, kasa/smart/smartdevice.py, kasa/tests/fakeprotocol_smart.py
Adds auto-off implementation. The feature stays enabled after the timer runs out, and it will start the countdown if the device is turned on again without explicitly disabling it.
New features:
* Switch to select if enabled: `Auto off enabled (auto_off_enabled): False`
* Setting to change the delay: `Auto off minutes (auto_off_minutes): 222`
* If timer is active, datetime object when the device gets turned off: `Auto off at (auto_off_at): None`
=> Auto auto-off module for smartdevice

kasa/smart/modules/__init__.py, kasa/smart/modules/firmware.py
Initial firmware module implementation.
New switch: `Auto update enabled (auto_update_enabled): False`
New binary sensor: `Update available (update_available): False`
TBD:
=> Add firmware module for smartdevice

kasa/smart/modules/__init__.py, kasa/tests/fakeprotocol_smart.py
#766 was merged too hastily to fail the tests as the module was never imported, this fixes that and adds the missing fixture data to the dummy fixture mapping.
=> Add missing firmware module import

kasa/smart/modules/firmware.py
Set the attribute_setter. Also, set the full payload data as it's expected (at least some) devices.
=> Fix auto update switch

kasa/cli.py, kasa/tests/conftest.py, kasa/tests/test_cli.py
This allows displaying and changing child device features that were previously not accessible using the cli tool:
```
kasa --host 192.168.xx  feature                                                              
No --type or --device-family and --encrypt-type defined, discovering for 5 seconds..
== Features ==
Device ID (device_id): xx
Signal Level (signal_level): 2
RSSI (rssi): -57
SSID (ssid): xx
Overheated (overheated): False
Alarm (alarm): False
Alarm source (alarm_source): None
Alarm sound (alarm_sound): Doorbell Ring 2
Alarm volume (alarm_volume): low
Cloud connection (cloud_connection): False
Auto update enabled (auto_update_enabled): False
Update available (update_available): False
LED (led): False
Time (time): 2024-02-22 23:23:51+01:00
== Child Temperature Humidity Sensor == …
```
=> Add --child option to feature command

kasa/feature.py, kasa/smart/modules/devicemodule.py, kasa/smart/modules/lighttransitionmodule.py, kasa/smart/smartmodule.py
Currently only v1 of on_off_gradually is supported, and the newer versions are not backwards compatible.
This PR adds support for the newer versions of the component, and implements `number` type for `Feature` to expose the transition time selection.
This also adds a new `supported_version` property to the main module class, we could also add a helper `raise_on_unsupported(component_name, minimum_version)` in the future if we encounter more similar cases.
Related to #792
=> Support for on_off_gradually v2+

.github/workflows/ci.yml
The pypy jobs are quite error prone, particularly the windows ones.
=> Do not fail fast on pypy CI jobs

kasa/device.py, kasa/smart/smartchilddevice.py, kasa/tests/test_smartdevice.py
Simplify `__repr__` for `Device`.
Previously:
```
>>> dev
<DeviceType.Hub model H100 at 192.168.xx.xx (Smart Hub), is_on: False - dev specific: {'overheated': False, 'signal_level': 2, 'SSID': 'xx'}>
>>> dev.children[0]
<ChildDevice Temperature Humidity Sensor of <DeviceType.Hub model H100 at 192.168.xx.xx (Smart Hub), is_on: False - dev specific: {'overheated': False, 'signal_level': 2, 'SSID': 'xx'}>>
```
Now:
```
>>> dev
Device: <DeviceType.Hub at 192.168.xx.xx - Smart Hub (H100)>
>>> dev.children[0]
<DeviceType.Sensor Temperature Humidity Sensor (T315) of <DeviceType.Hub at 192.168.xx.xx - Smart Hub (H100)>>
```
=> Simplify device __repr__

devtools/dump_devinfo.py, kasa/tests/device_fixtures.py, kasa/tests/discovery_fixtures.py, kasa/tests/fixtureinfo.py, kasa/tests/fixtures/smart/child/.gitkeep
This should prevent child fixtures from hubs breaking tests due to missing discovery info.  To get these devices in `filter_fixtures` include protocol string of `SMART.CHILD`.
=> Put child fixtures in subfolder

.github/workflows/ci.yml
Currently the CI is very slow for pypy vs cpython, one job is 24m vs 3m on cpython.  This PR enables poetry environment caching and bypasses coverage checking for pypy.
N.B. The poetry cache is keyed on a hash of the `poetry.lock` file.
*Before:*
*After:*
=> Do not run coverage on pypy and cache poetry envs

.github/workflows/ci.yml
Caching pre-commit halves the linting time and the `action/setup-python` cache does not handle `--extras` [properly ](https://github.com/actions/setup-python/issues/505) so switching to action/cache for the poetry cache
=> Add pre-commit caching and fix poetry extras cache

kasa/smart/modules/childdevicemodule.py, kasa/smart/smartdevice.py, kasa/tests/test_childdevice.py, kasa/tests/test_smartdevice.py
This improves the initial update cycle to fetch the information as early as possible and avoid requesting unnecessary information (like the child component listing) in every subsequent call of `update()`.
The initial update performs the following steps:
1. `component_nego` (for components) and `get_device_info` (for common device info) are requested as first, and their results are stored in the internal state to allow individual modules (like colortemp) to access the data during the initialization later on.
2. If `child_device` component is available, the child device list and their components is requested separately to initialize the children.
3. The modules are initialized based on component lists, making the queries available for the regular `update()`.
4. Finally, a query requesting …
=> Revise device initialization and subsequent updates

kasa/cli.py, kasa/device.py, kasa/iot/iotbulb.py, kasa/iot/iotdevice.py, kasa/iot/iotdimmer.py, kasa/iot/iotlightstrip.py, kasa/iot/iotplug.py, kasa/iot/iotstrip.py, kasa/smart/smartbulb.py, kasa/smart/smartdevice.py, kasa/tests/fakeprotocol_iot.py, kasa/tests/test_bulb.py, kasa/tests/test_lightstrip.py
`state_information` is repurposed to return a dictionary of feature-value pairs based on device-defined features.
Some of the previously existing information is not available anymore, and the naming of keys may have changed.
---
This PR changes `state_information` to return the names and values of all defined features.
It was originally a "temporary" hack to show some extra, device-specific information in the cli tool, but now that we have device-defined features we can leverage them.
=> Change state_information to return feature values

kasa/iot/iotbulb.py, kasa/tests/test_bulb.py
Make color temperature feature available for iot bulbs.
Should get merged after #804 is done.
=> Add colortemp feature for iot devices

kasa/tests/test_smartdevice.py
Issue slipped through due a problem with the CI https://github.com/python-kasa/python-kasa/pull/831
=> Fix non python 3.8 compliant test

.github/workflows/ci.yml
The [instructions](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md) for using the poetry cache in `actions/setup-python` appear to be erroneous.  pipx is installed before `actions/setup-python` is run so that the cache location is created, however this causes poetry to use the default python version rather than the version from `actions/setup-python`.  This PR drops the use of the `setup-python` cache altogether and just uses the `actions/cache` and ensures that pipx uses the python version from `actiona/setup-python`.
=> Fix CI issue with python version used by pipx to install poetry

.github/actions/setup/action.yaml, .github/workflows/ci.yml
Since fixing the issue with the python version that poetry uses in the CI https://github.com/python-kasa/python-kasa/pull/831 the `pipx install poetry` step has been taking a very long time, especially with pypy.
This PR caches the pipx install locations so poetry itself will be restored from the cache. It also moves all the install/setup logic into a custom action so it's not repeated unnecessarily and is easier to read and maintain.
=> Cache pipx in CI and add custom setup action

kasa/device_type.py, kasa/smart/modules/__init__.py, kasa/smart/modules/fanmodule.py, kasa/smart/smartchilddevice.py, kasa/smart/smartdevice.py, kasa/smart/smartmodule.py, kasa/tests/smart/modules/test_fan.py, kasa/tests/test_childdevice.py
This adds the final missing piece, the fan control module, for KS240 support:
```
== Features ==
Device ID (device_id): xx
Signal Level (signal_level): 3
RSSI (rssi): -41
SSID (ssid): xx
Brightness (brightness): 'brightness'
Cloud connection (cloud_connection): True
Fan speed level (fan_speed_level): 'fan_speed_level'
Fan sleep mode (fan_sleep_mode): 'fan_sleep_mode_on'
Auto update enabled (auto_update_enabled): False
Update available (update_available): True
LED (led): False
Smooth transition on (smooth_transition_on): argument of type 'SmartErrorCode' is not iterable
Smooth transition off (smooth_transition_off): argument of type 'SmartErrorCode' is not iterable
Time (time): You need to call update() prior accessing module data for 'time'
== Child Ceiling Fan ==
Device ID (device_id): …
```
=> Add fan module

kasa/iot/iotbulb.py, kasa/smart/smartbulb.py, kasa/tests/smart/features/test_brightness.py, kasa/tests/test_smartdevice.py
The allowed brightness for tested light devices (L530, L900) is [1-100] instead of [0-100] like it was for some kasa devices.
Related to #828.
Needs rebasing after #804 is merged.
=> smartbulb: Limit brightness range to 1-100

kasa/tests/test_cli.py
This unsets `KASA_` prefixed environment variables for cli tests, avoiding the annoying failures in auth tests if you have username and password defined in your environment.
As this is a fixture, we could potentially extend this to default `catch_exceptions=False` for `invoke()`.
=> Ignore system environment variables for tests

kasa/smart/modules/__init__.py, kasa/smart/modules/colormodule.py, kasa/smart/modules/colortemp.py, kasa/smart/smartbulb.py, kasa/smart/smartdevice.py, kasa/smart/smartmodule.py, kasa/tests/device_fixtures.py, kasa/tests/smart/features/test_colortemp.py, kasa/tests/test_bulb.py
Adds support L530 hw_version 1.0
Fixes https://github.com/home-assistant/core/issues/111757
=> Add ColorModule for smart devices

kasa/smartprotocol.py, kasa/tests/fakeprotocol_smart.py, kasa/tests/test_smartprotocol.py
When smart devices encounter an error during a multipleRequest they return the previous successes and the current error and stop processing subsequent requests.  This PR checks the responses returned and re-queries individually for any missing responses so that individual errors do not break other components.
=> Re-query missing responses after multi request errors

kasa/smart/modules/brightness.py, kasa/smart/smartbulb.py
Moves one more feature out from the smartbulb class
=> Use brightness module for smartbulb

kasa/device_type.py, kasa/smart/modules/__init__.py, kasa/smart/modules/temperaturecontrol.py, kasa/smart/smartchilddevice.py, kasa/tests/smart/modules/test_temperaturecontrol.py
This adds untested temperature_control module for smart devices, that can be used to control TRV devices.
Related to #847 which adds a fixture for KE100 needed to test this.
Fixes #422
=> Add temperature control module for smart

README.md
* Added https://github.com/mihai-dinculescu/tapo/ to the list of related projects.
* Changed the `kasa.tapo` to `kasa.smart`
=> Add rust tapo link to README

kasa/cli.py, kasa/device.py, kasa/feature.py, kasa/iot/iotbulb.py, kasa/iot/iotdevice.py, kasa/smart/modules/brightness.py, kasa/smart/modules/colortemp.py, kasa/smart/modules/fanmodule.py, kasa/smart/modules/ledmodule.py, kasa/smart/modules/reportmodule.py, kasa/smart/modules/timemodule.py, kasa/smart/smartdevice.py
Initial implementation for feature categories to help downstreams and our cli tool to categorize the data for more user-friendly manner. As more and more information is being exposed through the generic features interface, it is necessary to give some hints to downstreams about how might want to present the information to users.
This is not a 1:1 mapping to the homeassistant's mental model, and it will be necessary to fine-tune homeassistant-specific parameters by other means to polish the presentation.
=> Implement feature categories

kasa/feature.py, kasa/smart/modules/alarmmodule.py, kasa/tests/test_feature.py
Adds `FeatureType.Action` making it possible to expose features like "reboot", "test alarm", "pair" etc.
The `attribute_getter` is no longer mandatory, but it will raise an exception if not defined for other types than actions.
Trying to read returns a static string `<Action>`.
This overloads the `set_value` to call the given callable on any value.
This also fixes the `play` and `stop` coroutines of the alarm module to await the call.
=> Implement action feature

kasa/iot/iotbulb.py, kasa/iot/iotstrip.py, kasa/tests/fakeprotocol_iot.py, kasa/tests/fakeprotocol_smart.py, kasa/tests/smart/features/test_brightness.py, kasa/tests/smart/features/test_colortemp.py, kasa/tests/test_bulb.py, kasa/tests/test_cli.py, kasa/tests/test_dimmer.py, kasa/tests/test_lightstrip.py
Current implementations of `FakeSmartTransport` and `FakeIotProtocol` directly return their internal dictionaries which mean tests are able to see post update state changes without having to call `dev.update()`, unlike real world devices which would require an update.
=> Fix incorrect state updates in FakeTestProtocols

kasa/__init__.py, kasa/cli.py, kasa/feature.py, kasa/iot/iotbulb.py, kasa/iot/iotdimmer.py, kasa/iot/iotplug.py, kasa/iot/modules/ambientlight.py, kasa/iot/modules/cloud.py, kasa/smart/modules/alarmmodule.py, kasa/smart/modules/autooffmodule.py, kasa/smart/modules/battery.py, kasa/smart/modules/brightness.py, kasa/smart/modules/cloudmodule.py, kasa/smart/modules/colormodule.py, kasa/smart/modules/fanmodule.py, kasa/smart/modules/firmware.py, kasa/smart/modules/humidity.py, kasa/smart/modules/ledmodule.py, kasa/smart/modules/lighttransitionmodule.py, kasa/smart/modules/temperature.py, kasa/smart/modules/temperaturecontrol.py, kasa/smart/smartdevice.py, kasa/tests/test_feature.py
Moves `FeatureType` into `Feature` to make it easier to use the API.
This also enforces that no invalid types are accepted (i.e., `Category.Config` cannot be a `Sensor`)
If `--verbose` is used with the cli tool, some extra information is displayed for features when in the state command.
=> Embed FeatureType inside Feature

kasa/device_factory.py, kasa/tests/test_device_factory.py
Changes the device factory logic to allow constructing any devices from the SMART family, just logging a warning that it's an unknown device.
Fixes #768
=> Be more lax on unknown SMART devices

.github/workflows/ci.yml
https://github.com/actions/setup-python/issues/808
=> Fix broken CI due to missing python version on macos-latest

.github/actions/setup/action.yaml
The recent update to the `macos-latest` github runner changed the os architecture from x86_64 to arm64 which caused the application cache to have incompatible binaries.  This PR adds the `runner.arch` context variable to the cache keys to prevent this happening again. The manual workaround in this instance was to delete all the macos caches.
Action run for reference:
https://github.com/python-kasa/python-kasa/actions/runs/8828284579/job/24236995440
```
ImportError: dlopen(/Users/runner/work/python-kasa/python-kasa/pipx_cache/home/venvs/poetry/lib/python3.11/site-packages/charset_normalizer/md.cpython-311-darwin.so, 0x0002): 
tried: '/Users/runner/work/python-kasa/python-kasa/pipx_cache/home/venvs/poetry/lib/python3.11/site-packages/charset_normalizer/md.cpython-311-darwin.so' 
(mach-o …
```
=> Add runner.arch to cache-key in CI

kasa/iot/iotstrip.py, kasa/iot/modules/emeter.py
Exposes IOT emeter information using features, bases on #843 to allow defining the units.
Note, this doesn't currently pass mypy checks due to typing on some `emeter_*` properties which are currently defined to return an optional value.
Closes #772
=> Expose IOT emeter info as features

kasa/smartprotocol.py
Fixes issue currently only affecting `dump_devinfo` https://github.com/python-kasa/python-kasa/issues/875 but could also impact other device queries in the future.
=> Fix smartprotocol response list handler to handle null reponses

devtools/dump_devinfo.py, kasa/smartprotocol.py
While investigating dump_devinfo issue https://github.com/python-kasa/python-kasa/issues/875 the stack trace from the `print_stack` was unhelpful.  This PR prints the stack trace from the exception as if the exception was not caught.
=> Update dump_devinfo to print original exception stack on errors.

kasa/cli.py, kasa/device.py, kasa/iot/iotdevice.py, kasa/iot/iotstrip.py, kasa/module.py, kasa/smart/smartdevice.py, kasa/tests/smart/modules/test_fan.py, kasa/tests/test_smartdevice.py
Puts modules back on the children for `WallSwitches` (i.e. ks240) and makes them accessible from the `modules` property on the parent.
=> Put modules back on children for wall switches

kasa/feature.py, kasa/module.py, kasa/smart/modules/alarmmodule.py, kasa/smart/smartdevice.py, kasa/tests/discovery_fixtures.py, kasa/tests/test_cli.py, kasa/tests/test_feature.py
This implements the choice feature type allowing to provide a list of choices that can be set.
This changes the initialization a bit, as some choices, like the alarm tune, require that the device's module queries have been executed.
The implementation is done by adding a new `_initialize_features` to the module interface, which however fails to pass ruff as the interface is currently abstract. Thus I will mark this PR as draft for now, as I'm unsure what's the best approach here.
This could be also used for enum sensor types later on, to give hints to homeassistant about possible values a sensor can have.
=> Implement choice feature type

kasa/cli.py
Pass a dummy object as context object as it will not be used by --help anyway.
Also, allow defining --help anywhere in the argv, not just in the last place.
Fixes #885.
=> Fix --help on subcommands

kasa/smart/smartdevice.py
https://github.com/python-kasa/python-kasa/pull/862 updated the `SmartProtocol` to automatically get the remainder of lists with partial responses.  As a result the wifi_scan logic ends up querying twice and doubling the number of networks, as it doesn't check the returned count before trying another query.  The re-query logic can be removed entirely.
=> Fix wifi scan re-querying error

kasa/bulb.py, kasa/device.py, kasa/fan.py, kasa/smart/smartdevice.py
This is to bring consistency to the api across `Smart` and `Iot` so the interfaces can be used for their specialist methods as well as the device methods (e.g. turn_on/off) , i.e. a consumer can do:
```py
device = await Discover.discover_single(127.0.0.1)
if device.is_bulb:
bulb = cast(Bulb, device)
await bulb.turn_on()
await bulb.set_brightness(50)
if device.is_fan:
fan = cast(Fan, device)
await fan.turn_on()
await fan.set_fan_speed_level(3)
```
Once this is in we can start moving the documentation to the interfaces.
=> Update interfaces so they all inherit from Device

kasa/feature.py, kasa/iot/iotbulb.py, kasa/smart/modules/autooffmodule.py, kasa/smart/modules/colortemp.py, kasa/smart/modules/lighttransitionmodule.py, kasa/smart/modules/temperature.py, kasa/tests/device_fixtures.py, kasa/tests/test_feature.py
This adds a test to check that all feature.set_value() calls will cause a query, i.e., that there are no self.call()s that are not awaited, and fixes existing code in this context.
This also fixes an issue where it was not possible to print out the feature if the value threw an exception.
=> Improve feature setter robustness

devtools/dump_devinfo.py
This might fix saving of fixture files on Windows, but it's a good practice to use pathlib where possible.
=> Use Path.save for saving the fixtures

README.md, SUPPORTED.md, devtools/generate_supported.py, kasa/smart/smartdevice.py
Updates `generate_supported` hook to include child devices of hubs in the list of supported devices.
=> Add child devices from hubs to generated list of supported devices

kasa/feature.py, kasa/smart/modules/alarmmodule.py
Also logs a warning and fixes the returned string to be consistent with valid values.
=> Add missing alarm volume 'normal'

CONTRIBUTING.md, README.md, docs/source/contribute.md, docs/source/index.rst
Moves the instructions away from README.md to keep it simpler, and extend the documentation to be up-to-date and easier to approach.
=> Move contribution instructions into docs

kasa/device.py, kasa/iot/iotbulb.py, kasa/iot/iotdimmer.py, kasa/iot/iotlightstrip.py, kasa/iot/iotplug.py, kasa/iot/iotstrip.py, kasa/iot/modules/light.py, kasa/iot/modules/lighteffect.py, kasa/smart/modules/lightstripeffect.py, kasa/tests/test_device.py
Deprecates the attributes at device level for light, light effects, and led.  i.e. `device.led`, `device.is_color`.  Will continue to support consumers using these attributes and emit a warning
=> Deprecate device level light, effect and led attributes

kasa/module.py, kasa/smart/modules/lighteffect.py, kasa/smart/smartchilddevice.py, kasa/smart/smartdevice.py, kasa/tests/test_smartdevice.py
This PR adds a post update hook to modules so they can calculate values and collections once rather than on each property access.
To support this it moves the `_initialize_features` out of the child module creation so that it is guaranteed that all the hooks for a device's modules and it's children's modules will run before all `_initialize_features`.  This means that `_initialize_features` can rely on data initialized by `_post_update_hook`.
=> Add post update hook to module and use in smart LightEffect

kasa/__init__.py, kasa/interfaces/light.py, kasa/iot/iotbulb.py, kasa/iot/iotdimmer.py, kasa/iot/modules/light.py, kasa/smart/modules/light.py, kasa/tests/test_bulb.py, kasa/tests/test_common_modules.py, kasa/tests/test_dimmer.py
PR contains a number of fixes from testing with HA devices:
- Fixes a bug with turning the light on and off via `set_state`
- Aligns `set_brightness` behaviour across `smart` and `iot` devices such that a value of 0 is off.
- Aligns `set_brightness` behaviour for `IotDimmer` such that setting the brightness turns on the device with a transition of 1ms. ([HA comment](https://github.com/home-assistant/core/pull/117839#discussion_r1608720006))
- Fixes a typing issue in `LightState`.
- Adds `ColorTempRange` and `HSV` to `__init__.py`
- Adds a `state` property to the interface returning `LightState` for validating `set_state` changes.
- Adds tests for `set_state`
=> Fix set_state for common light modules

kasa/device.py, kasa/iot/iotdevice.py
This is allows a generic implementation for the switch platform in the homeassistant integration.
Also elevates set_state(bool) to be part of the standard API.
=> Add state feature for iot devices

kasa/cli.py
Running `--help` causes otherwise `Raised error: 0` when click wants to exit after showing the help.
=> Do not show a zero error code when cli exits from showing help

devtools/dump_devinfo.py
Seen in https://github.com/python-kasa/python-kasa/issues/937#issuecomment-2132207151
=> Fix passing custom port for dump_devinfo

kasa/smartprotocol.py, kasa/tests/test_smartprotocol.py
This will avoid crashing when some commands return an error on multi-requests on child devices.
Idea from https://github.com/python-kasa/python-kasa/pull/900/files#r1624803457
=> Do not raise on multi-request errors on child devices

CHANGELOG.md, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.7.0.dev1...0.7.0.dev2)
- Make device initialisation easier by reducing required imports [\#936](https://github.com/python-kasa/python-kasa/pull/936) (@sdb9696)
- Do not raise on multi-request errors on child devices [\#949](https://github.com/python-kasa/python-kasa/pull/949) (@rytilahti)
- Do not show a zero error code when cli exits from showing help [\#935](https://github.com/python-kasa/python-kasa/pull/935) (@rytilahti)
- Initialize autooff features only when data is available [\#933](https://github.com/python-kasa/python-kasa/pull/933) (@rytilahti)
- Fix P100 errors on multi-requests [\#930](https://github.com/python-kasa/python-kasa/pull/930) (@sdb9696) …
=> Prepare 0.7.0.dev2

kasa/tests/test_aestransport.py, poetry.lock, pyproject.toml
Reduces test time of device delay test from 2.2s to .75s.
=> Use freezegun for testing aes http client delays

kasa/smart/modules/fan.py, kasa/tests/smart/modules/test_fan.py
Picked this up while updating the [Fan platform PR](https://github.com/home-assistant/core/pull/116605) for HA. The smart fan module was not correctly deriving from the common interface and the speed_level is reported as >0 when off.
=> Fix fan speed level when off and derive smart fan module from common fan interface

kasa/aestransport.py
Issue encountered while connecting to P100 with the wrong `login_version` results in giving a misleading error message that cannot write to the client as opposed to the real `LOGIN_ERROR`.
=> Ensure http delay logic works during default login attempt

kasa/iot/modules/lighteffect.py, kasa/tests/fakeprotocol_iot.py, kasa/tests/test_common_modules.py
Previously there was not option to switch off a light effect.  Now there is the implemented method of setting enable to 0 does not work with a real device so this PR sets the light state to the previous state which switches off the effect.
=> Fix switching off light effects for iot lights strips

kasa/cli.py
Executing `wifi join` requires passing the current time information for smart devices which we read from the device.
This removes `wifi` from the block list to make it work.
It should be checked why this was added in the first place though..
=> Require update in cli for wifi commands

kasa/smart/smartdevice.py, kasa/tests/device_fixtures.py, kasa/tests/smart/features/test_brightness.py, kasa/tests/smart/modules/test_fan.py, kasa/tests/test_common_modules.py, kasa/tests/test_smartdevice.py
This PR removes the logic to expose child modules on parent devices.  Originally implemented to allow the ks240 to act as if the parent contains the child modules, it has been determined that this could cause complications with downstream consumers unknowingly duplicating things as a result.
=> Do not expose child modules on parent devices

kasa/smart/modules/lightpreset.py, kasa/smart/smartdevice.py
Replaces the logic to skip adding child modules to parent devices based on whether a device is a wall switch and instead relies on the `_check_supported` method.  Is more future proof and will fix issue with the P300 with child `auto_off` modules https://github.com/python-kasa/python-kasa/pull/915 not supported on the parent.
=> Better checking of child modules not supported by parent device

kasa/smart/modules/autooff.py, kasa/smart/smartchilddevice.py, kasa/smart/smartdevice.py, kasa/tests/fakeprotocol_smart.py, kasa/tests/smart/modules/test_autooff.py, kasa/tests/test_smartdevice.py
Required for the P300 firmware update with `auto_off` module on child devices. Will query child modules for parent devices that are not hubs.
Coverage will be fixed when the P300 fixture is added https://github.com/python-kasa/python-kasa/pull/915
=> Support smart child modules queries

SUPPORTED.md, kasa/tests/fixtures/smart/P300(EU)_1.0_1.0.15.json
This version adds auto-off for individual strip sockets.
=> Add fixture for p300 1.0.15

CHANGELOG.md, poetry.lock, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.7.0.dev3...0.7.0.dev4)
- Support smart child modules queries [\#967](https://github.com/python-kasa/python-kasa/pull/967) (@sdb9696)
- Do not expose child modules on parent devices [\#964](https://github.com/python-kasa/python-kasa/pull/964) (@sdb9696)
- Do not add parent only modules to strip sockets [\#963](https://github.com/python-kasa/python-kasa/pull/963) (@sdb9696)
**Project maintenance:**
- Better checking of child modules not supported by parent device [\#966](https://github.com/python-kasa/python-kasa/pull/966) (@sdb9696)
- Add fixture for p300 1.0.15 [\#915](https://github.com/python-kasa/python-kasa/pull/915) (@rytilahti)
=> Prepare 0.7.0.dev4

kasa/smart/modules/lighttransition.py
Fixes issue with ks240 adding module to parent:
```
== Configuration ==
Auto update enabled (auto_update_enabled): False
LED (led): False
Unable to read value (smooth_transition_on): argument of type 'SmartErrorCode' is not iterable
Unable to read value (smooth_transition_off): argument of type 'SmartErrorCode' is not iterable
```
Issue https://github.com/python-kasa/python-kasa/issues/970 created to track doing this for all smart modules for better future proofing.
=> Add supported check to light transition module

SUPPORTED.md, kasa/tests/fixtures/smart/L920-5(EU)_1.0_1.0.7.json
When not paired, the effect is softAP: `Light effect (light_effect): invalid value 'softAP' not in ['Off', 'Aurora', ...]`
=> Add fixture for L920-5(EU) 1.0.7

kasa/smart/modules/lightstripeffect.py
Fixes issue with unpaired devices reporting light effect as `softAP` reported in https://github.com/python-kasa/python-kasa/pull/972.  I don't think we need to handle that effect properly so just reports as off.
=> Handle unknown light effect names and only calculate effect list once

docs/source/cli.rst, kasa/cli.py, kasa/smart/modules/time.py, kasa/tests/test_cli.py
Allows setting the device time (on SMART devices) to the current time.
Fixes also setting the time which was previously completely broken.
TBD:
Fixes #852
Fixes #818
=> Add time sync command

kasa/device.py, kasa/interfaces/__init__.py, kasa/interfaces/energy.py, kasa/iot/iotbulb.py, kasa/iot/iotdevice.py, kasa/iot/iotstrip.py, kasa/iot/modules/emeter.py, kasa/iot/modules/led.py, kasa/module.py, kasa/smart/modules/energy.py, kasa/smart/smartdevice.py, kasa/tests/test_device.py, kasa/tests/test_emeter.py, kasa/tests/test_iotdevice.py
Decided to bite the bullet on this as it was starting to make the HR PR less simple.  Minimal changes to tests which should be reassuring.
Tested with `iot` hs300.
=> Add common energy module and deprecate device emeter attributes

CHANGELOG.md, poetry.lock, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.7.0.dev4...0.7.0.dev5)
- Add timezone to on\_since attributes [\#978](https://github.com/python-kasa/python-kasa/pull/978) (@sdb9696)
- Add common energy module and deprecate device emeter attributes [\#976](https://github.com/python-kasa/python-kasa/pull/976) (@sdb9696)
- Add type hints to feature set\_value [\#974](https://github.com/python-kasa/python-kasa/pull/974) (@sdb9696)
- Handle unknown light effect names and only calculate effect list once [\#973](https://github.com/python-kasa/python-kasa/pull/973) (@sdb9696)
- Add time sync command [\#951](https://github.com/python-kasa/python-kasa/pull/951) (@rytilahti)
- Disallow non-targeted device commands …
=> Prepare 0.7.0.dev5

poetry.lock, pyproject.toml
This is no longer required as it's correctly configured in [async click release 8.1.7.1](https://pypi.org/project/asyncclick/8.1.7.1/) released in January. 
Fixed in https://github.com/python-trio/asyncclick/pull/27
=> Remove anyio dependency from pyproject.toml

.github/workflows/ci.yml, .pre-commit-config.yaml, devtools/bench/benchmark.py, devtools/run-in-env.sh, kasa/aestransport.py, kasa/cli.py, kasa/httpclient.py, kasa/tests/discovery_fixtures.py, kasa/tests/fakeprotocol_smart.py, kasa/tests/smart/modules/test_firmware.py, kasa/tests/test_device.py, kasa/tests/test_emeter.py, kasa/tests/test_httpclient.py, kasa/tests/test_iotdevice.py, kasa/xortransport.py, poetry.lock, pyproject.toml
For some time I've noticed that my IDE is reporting mypy errors that the pre-commit hook is not picking up.  This is because [mypy mirror](https://github.com/pre-commit/mirrors-mypy) runs in an isolated pre-commit environment which does not have dependencies installed and it enables `--ignore-missing-imports` to avoid errors.
This is [advised against by mypy](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker) for obvious reasons:
> We recommend avoiding --ignore-missing-imports if possible: it’s equivalent to adding a # type: ignore to all unresolved imports in your codebase.
This PR configures the mypy pre-commit hook to run in the virtual environment and addresses the additional errors identified as a result. It also introduces a minimal …
=> Configure mypy to run in virtual environment and fix resulting issues

kasa/feature.py, kasa/smart/modules/temperaturesensor.py
Allow defining getter for unit, necessary to set the correct unit based on device responses.
TBD:
Fixes #923
=> Add unit_getter for feature

kasa/smart/modules/led.py, kasa/tests/test_cli.py
The behaviour of the led on most smart devices when set to "always" is:
- the led is on if the device is on
- the led is off if the device is off
It appears to be different for wall switches where the led is on/off if always/never respectively.
This PR changes the reporting of the state to match the setter which sets the rule to `always` or `never`. Will open a new issue to improve the shared interface to include the mode and determine whether the status is read only or not.
=> Fix smart led status to report rule status

kasa/smart/modules/time.py
This hides it from the entities enabled by default for HA.
=> Demote device_time back to debug

kasa/feature.py, kasa/interfaces/energy.py, kasa/iot/iotdevice.py, kasa/iot/iotstrip.py, kasa/smart/modules/alarm.py, kasa/smart/modules/autooff.py, kasa/smart/modules/firmware.py, kasa/smart/modules/humiditysensor.py, kasa/smart/modules/reportmode.py, kasa/smart/modules/temperaturecontrol.py, kasa/smart/modules/temperaturesensor.py, kasa/smart/modules/time.py, kasa/smart/modules/waterleaksensor.py, kasa/smart/smartdevice.py, kasa/tests/test_feature.py
Explicit > implicit. Having this previously would have avoided using a wrong type for water_alert in the first place.
=> Require explicit feature type

kasa/iot/iotstrip.py, kasa/tests/test_strip.py
`_post_update_hook` not being called on child `iot` devices, causing missing emeter features for children
=> Fix post update hook for iot child devices

kasa/smart/modules/lighttransition.py
Module is not working properly for updates on KS240 so temporarily disable until fixed
=> Disable lighttransition module on child devices

kasa/aestransport.py, kasa/exceptions.py, kasa/smartprotocol.py, kasa/tests/test_aestransport.py, kasa/tests/test_smartprotocol.py
Makes unknown error codes to be reported through KasaException which may be recoverable in some cases (i.e., a single command failing in the multi request).
Related to https://github.com/home-assistant/core/issues/118446
=> Handle unknown error codes gracefully

kasa/aestransport.py, kasa/exceptions.py, kasa/smartprotocol.py
Avoid the `__call__` and `__new__` overhead to create the singleton by caching the creation.  Since we never overload methods or subclass these, we can avoid all the complexity most of the time. This is a tiny optimization.
before:
after
=> Cache SmartErrorCode creation

.github_changelog_generator, RELEASING.md
Move the static command line options into the config file for consistency and remove `--no-issues` in favour of `issues-wo-labels=false` to fix the problem where `release-summary` issues are being excluded from the changelog.
=> Update changelog generator config

devtools/helpers/smartrequests.py, kasa/smart/modules/autooff.py, kasa/smart/modules/batterysensor.py, kasa/smart/modules/cloud.py, kasa/smart/modules/devicemodule.py, kasa/smart/modules/firmware.py, kasa/smart/modules/frostprotection.py, kasa/smart/modules/humiditysensor.py, kasa/smart/modules/lightpreset.py, kasa/smart/modules/lighttransition.py, kasa/smart/modules/reportmode.py, kasa/smart/modules/temperaturesensor.py, kasa/smart/smartdevice.py, kasa/smart/smartmodule.py, kasa/smartprotocol.py, kasa/tests/test_smartdevice.py, kasa/tests/test_smartprotocol.py
This PR ensures that all modules try to access their `data` in `_post_update_hook` in a safe manner and disable themselves if there's an error.
It also adds parameters to `get_preset_rules` and `get_on_off_gradually_info` to fix issues with recent firmware updates. https://github.com/python-kasa/python-kasa/issues/1033.
=> Handle module errors more robustly and add query params to light preset and transition

CHANGELOG.md, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.7.0.2...0.7.0.3)
Critical bugfix for issue #1033 with ks225 and S505D light preset module errors.
Partially fixes light preset module errors with L920 and L930.
Handle module errors more robustly and add query params to light preset and transition [\#1043](https://github.com/python-kasa/python-kasa/pull/1043)
=> Prepare 0.7.0.3

kasa/smart/modules/lightpreset.py, kasa/tests/fixtures/smart/L920-5(EU)_1.0_1.1.3.json
Fixes the residual issues with the light preset module not handling unexpected `lighting_effect` items in the presets list.
Completes the fixes started with PR https://github.com/python-kasa/python-kasa/pull/1043 to fix https://github.com/python-kasa/python-kasa/issues/1040, [HA #121115](https://github.com/home-assistant/core/issues/121115) and [HA #121119](https://github.com/home-assistant/core/issues/121119)
With this PR affected devices will no longer have the light preset functionality disabled.  As this is a new feature this does not warrant a hotfix so will go into the next release.
Updated fixture for testing thanks to @szssamuel, many thanks!
=> Fix light preset module when list contains lighting effects

kasa/smart/modules/temperaturecontrol.py, kasa/tests/smart/modules/test_temperaturecontrol.py
Instead of trying to use the first state when multiple are reported, iterate over the known states and pick the first matching.
This will fix an issue where the device reports extra states (like `low_battery`) while having a known mode active.
Related to https://github.com/home-assistant/core/issues/121335
=> Use first known thermostat state as main state

kasa/aestransport.py, kasa/exceptions.py, kasa/httpclient.py, kasa/smart/modules/cloud.py, kasa/smart/modules/firmware.py, kasa/smart/modules/led.py, kasa/smart/modules/lighteffect.py, kasa/smart/modules/lightpreset.py, kasa/smart/modules/lightstripeffect.py, kasa/smart/modules/lighttransition.py, kasa/smart/smartchilddevice.py, kasa/smart/smartdevice.py, kasa/smart/smartmodule.py, kasa/smartprotocol.py, kasa/tests/test_smartdevice.py, kasa/tests/test_smartprotocol.py
Addresses stability issues on older hw device versions
- Handles module timeout errors better by querying modules individually on errors and disabling problematic modules like Firmware that go out to the internet to get updates.
- Addresses an issue with the Led module on P100 hardware version 1.0 which appears to have a memory leak and will cause the device to crash after approximately 500 calls.
- Delays updates of modules that do not have regular changes like LightPreset and LightEffect and enables them to be updated on the next update cycle only if required values have changed.
=> Defer module updates for less volatile modules (pick 1052)

kasa/smart/modules/temperaturecontrol.py, kasa/tests/smart/modules/test_temperaturecontrol.py
Pick of https://github.com/python-kasa/python-kasa/pull/1054
Instead of trying to use the first state when multiple are reported, iterate over the known states and pick the first matching.
This will fix an issue where the device reports extra states (like low_battery) while having a known mode active.
Related to https://github.com/home-assistant/core/issues/121335
=> Use first known thermostat state as main state (pick #1054)

CHANGELOG.md, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.7.0.3...0.7.0.4)
Critical bugfixes for issues with P100s and thermostats.
- Use first known thermostat state as main state (pick #1054) [\#1057](https://github.com/python-kasa/python-kasa/pull/1057)
- Defer module updates for less volatile modules (pick 1052) [\#1056](https://github.com/python-kasa/python-kasa/pull/1056)
=> Prepare 0.7.0.4

kasa/httpclient.py, kasa/klaptransport.py, kasa/smart/smartdevice.py, kasa/smartprotocol.py, kasa/tests/test_smartdevice.py
To fix intermittent issues with [windows CI](https://github.com/python-kasa/python-kasa/actions/runs/9952477932/job/27493918272?pr=1068). Probably better to use monotonic here anyway.
```
FAILED kasa/tests/test_smartdevice.py::test_update_module_update_delays[L530E(EU)_3.0_1.1.6.json-SMART] - ValueError: Clock moved backwards. Refusing to generate ID.
```
=> Use monotonic time for query timing

kasa/smart/modules/lighteffect.py
Fixes an issue with L530 bulbs on HW version 1.0 whereby the light effect query causes the device to crash with `JSON_ENCODE_FAIL_ERROR` after approximately 60 calls.
Similar behaviour to the `get_led_info` issue fixed in https://github.com/python-kasa/python-kasa/pull/1052 except setting an effect does not fix the device like it did with the Led rule.
Fixes [HA issue #121362](https://github.com/home-assistant/core/issues/121362) although the devices could still fail after around 60 days if not restarted in the meantime.
Many thanks to @zetaho2003 for helping with the testing for this issue.
=> Only refresh smart LightEffect module daily

devtools/parse_pcap_klap.py
A few fixes:
- Issue running pyshark on new thread in windows
- Bug if handshake repeated during capture
- Also tries default credentials as per the library
Tested on linux and windows
=> Fix parse_pcap_klap on windows and support default credentials

kasa/klaptransport.py, kasa/tests/test_klapprotocol.py
Currently if the library encounters an invalid decryption error it raises a value error.  This PR wraps it in a KasaException so consumers such as HA can catch an expected library exception.
=> Raise KasaException on decryption errors

kasa/smart/modules/led.py, kasa/smart/modules/lightpreset.py, kasa/smart/modules/lighttransition.py, kasa/smartprotocol.py, kasa/tests/fakeprotocol_smart.py
Update smart request parameters based on TAPO app requests. Highlights are:
- App does not send `params` if null.  This should stop the issues we've been getting with devices complaining about parameters randomly.
- `get_preset_rules` doesn't send parameters for `preset` component version less than 3 (confirmed version 3 in the de-compiled app)
- `get_led_info` no longer sends the wrong parameters
- `get_on_off_gradually_info` no longer sends an empty `{}` parameter
- The PR also drops the `requestId` parameter which the app doesn't send and afaict was added to the py100 library for no reason.
- Note that the app only queries `get_device_info` once and then queries `get_device_running_info`. We should consider this as I noted when investigating various `JSON_ENCODE_FAIL_ERROR` issues that …
=> Update smart request parameter handling

docs/tutorial.py, kasa/device.py, kasa/feature.py, kasa/iot/iotdevice.py, kasa/smart/smartdevice.py
Expose reboot through the feature interface.
This can be useful in situations where one wants to reboot the device, e.g., in recent cases where frequent update calls will render the device unresponsive after a specific amount of time.
As I don't have access to test devices at the moment, this has not been tested against a real device.
=> Expose reboot action

kasa/tests/test_klapprotocol.py
Caused due to the error from using the wrong encryption not being consistent.
https://github.com/python-kasa/python-kasa/actions/runs/10077920368/job/27861718880
=> Fix intermittently failing decryption error test

.pre-commit-config.yaml, devtools/run-in-env.sh
I noticed after building a new linux instance that running `git commit` when the virtual environment is not active causes the pre-commit to fail, as the `generate_supported` hook is not explicitly configured to run in the virtual env.  This PR calls `generate_supported` via the `run-in-env.sh` script.
=> Fix generate_supported pre commit to run in venv

kasa/feature.py, kasa/iot/iotbulb.py, kasa/smart/modules/colortemperature.py, kasa/smart/modules/light.py, kasa/tests/test_common_modules.py
Fixes [HA Issue 122401](https://github.com/home-assistant/core/issues/122401)
The addition of the tests here highlighted that the iot module was calling the deprecated `valid_temperature_range` function on the device. Whilst debugging I discovered that nesting `cached_property` prevents the debugger from accessing the lower level property so removed the `cached_property` for maximum and minimum values.
=> Enable setting brightness with color temp for smart devices

kasa/tests/test_readme_examples.py, poetry.lock, pyproject.toml
This is now natively supported since [xdoctest #158](https://github.com/Erotemic/xdoctest/pull/158) has been released so no need for the monkey patching fixture anymore.
=> Remove top level await xdoctest fixture

kasa/iot/iotdevice.py
This debug logger was generating the `repr()` of each module and throwing it away because it had a `%` instead of a `,`
=> Fix logging in iotdevice when a module is module not supported

poetry.lock, pyproject.toml
`typing_extensions` is a dependency of `pydantic` so it's getting installed by default but it should be an explicit dependency of python-kasa.
=> Add missing typing_extensions dependency

kasa/aestransport.py, kasa/device_factory.py, kasa/discover.py, kasa/emeterstatus.py, kasa/iot/iotdevice.py, kasa/klaptransport.py, kasa/smart/modules/firmware.py, kasa/smart/smartmodule.py, kasa/smartprotocol.py, kasa/tests/fakeprotocol_iot.py, pyproject.toml
Enables rules LOG (flake8-logging) and G (flake8-logging-format) for ruff. This will catch eager log message formatting, among other similar issues.
=> Add flake8-logging (LOG) and flake8-logging-format (G) for ruff

CHANGELOG.md, RELEASING.md, poetry.lock, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.7.1...0.7.2)
**Release summary:**
- **Breaking** change to disable including the check for the latest firmware for tapo devices and newer kasa devices in the standard update cycle. To check for the latest firmware call `check_latest_firmware` on the firmware module or run the `check_latest_firmware` feature.
- Minor bugfixes and improvements.
**Breaking changes:**
- Disable automatic updating of latest firmware [\#1103](https://github.com/python-kasa/python-kasa/pull/1103) (@sdb9696)
- Improve performance of dict merge code [\#1097](https://github.com/python-kasa/python-kasa/pull/1097) (@bdraco)
- Fix logging in iotdevice when a module is module not supported …
=> Prepare 0.7.2

kasa/aestransport.py, kasa/deviceconfig.py, kasa/tests/test_aestransport.py
And read it from `device_config` if provided.
This is required as key generation can eat up cpu when a device is not fully available and the library is retrying.
=> Do not regenerate aes key pair

kasa/device.py
Both device families have already had a method following this signature, but defining the interface in the base class will make the contract clear.
=> Add reboot() to the device interface

kasa/iot/iotbulb.py
Apparently (newer?) KL135 bulbs support ct ranges up to 9000K as reported at https://github.com/home-assistant/core/issues/126300 .
[tplink-smarthome-api](https://github.com/plasticrake/tplink-smarthome-api/blob/33f55531e6d5935d57a065fb95fa5dc340c4f392/src/bulb/index.ts#L38) is also using this range, and it is the same as mentioned in the official manual, so I think we can also extend this.
[The original reporter for the missing ct range](https://github.com/python-kasa/python-kasa/issues/252#issuecomment-974187853) had a KL135 marketed only to support up to 6500K, but I don't see any relevant changes in the fixture (#1122) that could be used to differentiate between these versions.
Related to https://github.com/home-assistant/core/issues/126300
=> Extend KL135 ct range up to 9000K

kasa/tests/test_bulb.py, kasa/tests/test_common_modules.py, pyproject.toml
Addresses repeated SyntaxWarnings when running linters:
```
kasa/tests/test_bulb.py:254: SyntaxWarning: invalid escape sequence '\d'
ValueError, match="Temperature should be between \d+ and \d+, was 1000"
kasa/tests/test_bulb.py:258: SyntaxWarning: invalid escape sequence '\d'
ValueError, match="Temperature should be between \d+ and \d+, was 10000"
kasa/tests/test_common_modules.py:216: SyntaxWarning: invalid escape sequence '\d'
with pytest.raises(ValueError, match="Temperature should be between \d+ and \d+"):
kasa/tests/test_common_modules.py:219: SyntaxWarning: invalid escape sequence '\d'
with pytest.raises(ValueError, match="Temperature should be between \d+ and \d+"):
```
=> Enable ruff lint pycodestyle warnings

.github/workflows/stale.yml
If approved we need to create the `stale`, `no-stale`, `needs-more-information`, and `waiting-for-reporter` labels before merging.
=> Add stale PR/Issue github workflow

kasa/cli/device.py
Noticed it's missed when using the full `kasa device off` command as opposed to the shortcut.
=> Fix cli command for device off

kasa/device.py, kasa/iot/iotdevice.py
This adds support for device factory reset for IOT devices, tested on KP303.
Also extends the base device class API to make `factory_reset()` to be a part of the common API. This could be extracted into its own PR, if needed.
=> Add factory_reset() to iotdevice

devtools/parse_pcap_klap.py
tshark 4.4.0 does not have response_for_uri, this fixes response detection by using request_uri, too.
=> parse_pcap_klap: use request_uri for matching the response

devtools/parse_pcap_klap.py
The current logic does not accommodate when multiple hosts are communicating with the target device.
This adds a mandatory --source-host to make sure the correct handshake is captured.
=> parse_pcap_klap: require source host

devtools/dump_devinfo.py, kasa/device_factory.py, kasa/discover.py, kasa/iot/iotdevice.py, kasa/klaptransport.py
Fixes: #1120
UDP query from TAPO app is
```
{"system":{"get_sysinfo":{}},"cnCloud":{"get_info":{}},"smartlife.iot.common.cloud":{"get_info":{}},"smartlife.cam.ipcamera.cloud":{"get_info":{}}}
```
=> Send empty dictionary instead of null for iot queries

kasa/device.py, kasa/iot/iotdevice.py, kasa/iot/iotstrip.py, kasa/smart/smartdevice.py
Should address [HA issue 126852](https://github.com/home-assistant/core/issues/126852).
It's difficult to know for certain how many seconds to set this to but I suspect the variation is just 1 second.
=> Stabilise on_since value for smart devices

kasa/smart/smartmodule.py
The `SmartModule.call` function is always awaited and always calls an awaitable so it should be defined as an `async` function.
=> Correctly define SmartModule.call as an async function

kasa/tests/conftest.py, kasa/tests/test_device.py, kasa/tests/test_feature.py, kasa/tests/test_protocol.py
Not required since AsyncMock available in python 3.8 and probably better to keep magic to a minimum.
=> Remove async magic patch from tests

kasa/iot/modules/time.py
Using `astime` on a non tzinfo aware object causes issues with daylight saving.
=> Use tzinfo in time constructor instead of astime for iot devices

kasa/aestransport.py, kasa/cli/discover.py, kasa/cli/main.py, kasa/discover.py, kasa/tests/test_aestransport.py, kasa/tests/test_cli.py, kasa/tests/test_discovery.py
Enables the new type of 20002 discovery used by Tapo Cameras and the H200 hub.  Will report devices supporting this protocol as unsupported and display the discovery info.
Thanks to @rytilahti for doing the initial work on this.
Example discovery output:
```
Discovering device 192.168.1.X for 10 seconds
== Unsupported device ==
== Discovery Result ==
Device Type:        SMART.IPCAMERA
Device Model:       C210
Device Name:        Foobar cam
IP:                 192.168.1.X
MAC:                40-AE-30-00-00-00
Device Id (hash):   1234566459897ABCDEF
FW Ver:             1.4.2 Build 240829 Rel.54953n
HW Ver:             2.0
Supports IOT Cloud: True
Encrypt Type:       ['3']
Supports HTTPS:     True
Encrypt info:       EncryptionInfo(sym_schm='AES',
key='long b64 key',
data='long b64 data') …
```
=> Enable newer encrypted discovery protocol

.gitattributes
Looks like everything was fine, but let's do this nevertheless.
=> Enforce EOLs for *.rst and *.md

kasa/cli/discover.py, kasa/device_factory.py, kasa/discover.py, kasa/exceptions.py, kasa/tests/discovery_fixtures.py, kasa/tests/test_cli.py, kasa/tests/test_device_factory.py, kasa/tests/test_discovery.py
The Tapo H200 has a device family of SMART.TAPOHUB but uses the new SmartCamera protocol so the additional https parameter is required to distuingish between them.
=> Add https parameter to device class factory

kasa/smart/modules/devicemodule.py, kasa/smart/modules/time.py, kasa/smart/smartdevice.py, kasa/tests/test_childdevice.py
No devices in `fixtures/smart/child` support the `get_device_time` or `get_device_usage` methods so this PR tests for whether the device is a hub child and marks those modules/methods as not supported. This prevents features being erroneously created on child devices.
It also moves the logic for getting the time from the parent module behind getting it from the child module which was masking the creation of these unsupported modules.
=> Improve supported module checks for hub children

kasa/tests/fakeprotocol_smart.py, kasa/tests/fakeprotocol_smartcamera.py, kasa/tests/fixtureinfo.py, kasa/tests/test_emeter.py
Required for the P304M which uses energy modules directly on the child devices.
=> Update SMART test framework to use fake child protocols

kasa/iot/iotplug.py, kasa/tests/iot/test_wallswitch.py
Some devices (like KS200M) support ambient and motion, but as they are detected as wall switches, they don't get the modules added.
This PR enables the respective modules for wall switches when the `dev_name` contains `PIR`.
Fixes #1226
=> Add PIR&LAS for wall switches mentioning PIR support

kasa/device.py, kasa/smart/smartdevice.py, kasa/tests/test_discovery.py
This PR will make `__repr__` also work on smartdevices where only discovery data is available by modifying the `model` property to fallback to the data found in the discovery payloads.
May fix #1232
=> Make __repr__ work on discovery info

kasa/cli/light.py
Now prints presets as such:
```
[0] Hue:   0  Saturation:   0  Brightness/Value: 100  Temp: 6000  Custom: None  Mode: None  Id: None
[1] Hue:   0  Saturation:   0  Brightness/Value: 100  Temp: 2500  Custom: None  Mode: None  Id: None
[2] Hue:   0  Saturation:   0  Brightness/Value:  60  Temp: 2500  Custom: None  Mode: None  Id: None
[3] Hue: 240  Saturation: 100  Brightness/Value: 100  Temp:    0  Custom: None  Mode: None  Id: None
```
Apparently NoneType doesn't like f-strings (`unsupported format string passed to NoneType.__format__`), so I didn't add spaced formatting to the last 3 properties.
=> Print formatting for IotLightPreset

SUPPORTED.md, kasa/tests/fixtures/ES20M(US)_1.0_1.0.11.json, kasa/tests/test_dimmer.py
Fixture by courtesy of JetSerge on the HA community forums.
This is the first one to contain `get_current_brt` (#1209).
=> Update fixture for ES20M 1.0.11

devtools/parse_pcap.py, devtools/parse_pcap_klap.py, docs/source/reference.md, kasa/__init__.py, kasa/device.py, kasa/device_factory.py, kasa/discover.py, kasa/experimental/sslaestransport.py, kasa/iotprotocol.py, kasa/protocol.py, kasa/smart/smartdevice.py, kasa/smartprotocol.py, kasa/transports/__init__.py, kasa/transports/aestransport.py, kasa/transports/basetransport.py, kasa/transports/klaptransport.py, kasa/transports/xortransport.py, tests/conftest.py, tests/discovery_fixtures.py, tests/fakeprotocol_iot.py, tests/fakeprotocol_smart.py, tests/fakeprotocol_smartcamera.py, tests/test_aestransport.py, tests/test_discovery.py, tests/test_klapprotocol.py, tests/test_protocol.py, tests/test_sslaestransport.py
This moves all transport implementations into a new `transports` package for cleaner main package & easier to understand project structure.
Open todos:
=> Move transports into their own package

pyproject.toml, uv.lock
As of today it seems readthedocs is using python 3.13 for builds and is now failing as the sphinx version needs to >= 6.2.
https://github.com/python/cpython/issues/104818
=> Update sphinx dependency to 6.2 to fix docs build

kasa/deviceconfig.py, tests/conftest.py, tests/fixtures/serialization/deviceconfig_camera-aes-https.json, tests/fixtures/serialization/deviceconfig_plug-klap.json, tests/fixtures/serialization/deviceconfig_plug-xor.json, tests/test_deviceconfig.py
This PR simplifies the deviceconfig serialization to use Mashumaro instead of custom serialization.
It is a breaking change as the `deviceconfig.to_dict()` that takes parameters to control serialization of credentials is renamed to `to_dict_control_credentials()`. This should not have much impact as calling `to_dict()` with no parameters has the same behaviour and HA no longer serializes the entire deviceconfig.
The first commit adds tests against the previous implementation, the second does the conversion.
=> Replace custom deviceconfig serialization with mashumaru

devtools/dump_devinfo.py, tests/fixtures/KL130(EU)_1.0_1.8.8.json
* Some devices (like iot bulbs) use a different module names, this fixes dumping for the cloud interface
* Updates KL130 fixture, containing new additions from #1278
=> dump_devinfo: query smartlife.iot.common.cloud for fw updates

tests/fixtureinfo.py
Not easy to control this with a command option because the fixture filtering happens when the module is loaded.
=> Do not print out all the fixture names at the start of test runs

devtools/helpers/smartrequests.py, tests/fixtures/smart/KP125M(US)_1.0_1.2.3.json
- Add: `get_emeter_data` to SMART requests.
- Add: `get_emeter_vgain_igain` to SMART requests.
=> Add SMART Voltage Monitoring to Fixtures

kasa/__init__.py, kasa/cli/light.py, kasa/device.py, kasa/interfaces/energy.py, kasa/iot/iotdimmer.py, kasa/iot/iotmodule.py, kasa/iot/iotstrip.py, kasa/iot/modules/light.py, kasa/smart/smartdevice.py, tests/test_emeter.py
With 0.8 I think it's time to drop the deprecated attributes from type checkers. This PR does that and fixes the hidden issues arising.
=> Exclude __getattr__ for deprecated attributes from type checkers

devtools/dump_devinfo.py, tests/fixtures/ES20M(US)_1.0_1.0.11.json, tests/fixtures/KL135(US)_1.0_1.0.15.json, tests/fixtures/KS200M(US)_1.0_1.0.10.json, tests/fixtures/KS220(US)_1.0_1.0.13.json
Updated LAS/PIR fixtures:
- Add: `get_dark_status` for LAS enabled IOT devices.
- Add: `get_adc_value` for LAS enabled IOT devices.
- Add: `get_adc_value` for PIR enabled IOT devices.
Also made updates to the following fixtures as a bonus:
- Add: Updated test fixture for KL135 showing updated `lightingservice` response.
- Add: Real values for `get_default_behavior` from KS220.
=> Add PIR ADC Values to Test Fixtures

pyproject.toml, tests/conftest.py, tests/iot/modules/test_schedule.py, tests/smart/modules/test_firmware.py, tests/smart/modules/test_temperaturecontrol.py, tests/test_aestransport.py, tests/test_bulb.py, tests/test_childdevice.py, tests/test_device_factory.py, tests/test_discovery.py, tests/test_feature.py, tests/test_klapprotocol.py, tests/test_protocol.py, tests/test_smartdevice.py, tests/test_smartprotocol.py, tests/test_sslaestransport.py
Fixes issue causing test failures: https://github.com/python-kasa/python-kasa/actions/runs/11983779130?pr=1303
Experimented with trying to do this centrally in the third commit but it didn't work. Will go with this for now and merge to fix the broken CI pipeline.
=> Run tests with caplog in a single worker

kasa/cli/main.py, kasa/cli/usage.py, kasa/smart/modules/energy.py, tests/test_cli.py, tests/test_emeter.py
Make `kasa energy` work again.
Also removes  the deprecated `emeter` which never worked as it was not exposed to the cli.
This was not discovered earlier as the test accessed the command directly, so this PR also changes its test to call `kasa energy`.
Fixes #1306
=> Expose energy command to cli

kasa/smart/modules/lighttransition.py
S505D expects the `duration` key being passed even when the setting is disabled, so this PR adds it from the cache.
Requires testing on more devices to see if we can do this, or if we need to add some special handling for that specific device.
Fixes #1309
=> Include duration when disabling smooth transition on/off

kasa/smartcam/smartcamdevice.py
It occured to me that if we get encounter an H200 with smartcam protocol children the smart child initialization will completely fail so this ensures that doesn't happen.
=> Do not error on smartcam hub attached smartcam child devices

kasa/cli/discover.py, kasa/discover.py, tests/discovery_fixtures.py
This should reduce confusion around tplink homewifi systems that have a discovery response without this data.
[HA Issue comment](https://github.com/home-assistant/core/issues/123651#issuecomment-2293719325)
[Kasa Homebridge Plugin](https://github.com/ZeliardM/homebridge-kasa-python/issues/4#issuecomment-2492635938)
=> Handle missing mgt_encryption_schm in discovery

tests/smart/modules/test_autooff.py
We don't support old python versions anymore, so this can go.
=> Remove unnecessary check for python <3.10

kasa/smart/smartdevice.py, tests/discovery_fixtures.py, tests/smart/test_smartdevice.py
Fixes exception raised accessing `device_type` before `update()` in [Homebridge kasa plug in](https://github.com/ZeliardM/homebridge-kasa-python/issues/4)
=> Do not error when accessing smart device_type before update

kasa/cli/discover.py, kasa/discover.py, kasa/json.py, tests/test_cli.py
Adds `on_discovered_raw` callback to `Discover` and adds a cli command `discover raw` which returns the raw json before serializing to a `DiscoveryResult` and attempting to create a device class.
=> Return raw discovery result in cli discover raw

docs/tutorial.py, kasa/feature.py, kasa/smart/modules/__init__.py, kasa/smart/modules/contactsensor.py, kasa/smart/modules/overheatprotection.py, kasa/smart/smartdevice.py, kasa/smart/smartmodule.py, tests/smart/test_smartdevice.py
Different devices and different firmwares report overheated status in different ways.
Some devices indicate support for `overheat_protect` component, but there are devices that report `overheat_status` even when it is not listed.
Some other devices use `overheated` boolean that was already previously supported, but this PR adds support for much more devices that use `overheat_status` for reporting.
The "overheated" feature is moved into its own module, and uses either of the ways to report this information.
This will also rename `REQUIRED_KEY_ON_PARENT` to `SYSINFO_LOOKUP_KEYS` and change its logic to check if any of the keys in the list are found in the sysinfo.
```
tpr@lumipyry ~/c/p/tests (fix/overheated)> ag 'overheat_protect' -c|wc -l
15
tpr@lumipyry ~/c/p/tests (fix/overheated)> ag …
```
=> Improve overheat reporting

kasa/smart/smartchilddevice.py, kasa/smart/smartdevice.py, kasa/smartcam/smartcamdevice.py, tests/test_childdevice.py, tests/test_device.py
Cleans up and consolidates up the processing of raw component query responses.
Will simplify the code paths for creating smartcam child devices when supported.
Also addresses the [question raised](https://github.com/python-kasa/python-kasa/pull/1338#discussion_r1870911802) in the PR for consistent use of `DeviceInfo`
=> Pass raw components to SmartChildDevice init

README.md
https://github.com/ZeliardM/homebridge-kasa-python uses this library to provide homekit bridging.
Ping @ZeliardM
=> Add homebridge-kasa-python link to README

kasa/cli/device.py, kasa/device.py, kasa/discover.py, kasa/iot/iotdevice.py, kasa/smart/smartchilddevice.py, kasa/smart/smartdevice.py, kasa/smartcam/smartcamdevice.py, tests/device_fixtures.py, tests/iot/test_iotdevice.py, tests/smart/test_smartdevice.py, tests/test_discovery.py, tests/test_readme_examples.py
**This PR will make model exclude the region for `iot` devices. This will be consistent with `smart` and `smartcam` devices. `region` is now available as it's own attribute. This could be considered a breaking change depending on usage of the model string.**
- Ensures that devices are consistently using their  `_get_device_info` static methods for all information relating to device model information.
- Fixes issue with firmware and hardware being the wrong way round for `smartcam` devices.
=> Use DeviceInfo consistently across devices

kasa/protocols/smartprotocol.py, tests/fakeprotocol_smartcam.py, tests/protocols/test_smartprotocol.py
Required for `onboarding` requests included in https://github.com/python-kasa/python-kasa/pull/1373 which do not return the `method` key and need to be sent as single requests.
=> Force single for some smartcam requests

kasa/cli/discover.py, tests/discovery_fixtures.py, tests/test_cli.py
```
kasa --target 192.168.xx.xx discover list
HOST            MODEL     DEVICE FAMILY        ENCRYPT HTTPS LV  ALIAS
192.168.xxx.xxx KP115(EU) IOT.SMARTPLUGSWITCH  XOR     0     -   Fridge
192.168.xxx.xxx L900-5    SMART.TAPOBULB       KLAP    0     2   L900
192.168.xxx.xxx P115      SMART.TAPOPLUG       AES     0     2   Nightdesk
192.168.xxx.xxx TC65      SMART.IPCAMERA       AES     1     2   Tapo_TC65_B593
```
Also handles `TimeoutError` and `Exception` during `update()`
=> cli: print model, https, and lv for discover list

kasa/smartcam/modules/camera.py, kasa/smartcam/modules/lensmask.py
Fixes a few issues with the lens mask since migrating it into its own module:
- The module didn't provide itself as the container and hence the feature was accessing the same properties on the device.
- `enabled` getter on the module incorrect but not picked up due to the previous issue.
- No `REQUIRED_COMPONENT` set to ensure the module only created if available.
Also changes attribute names to `enabled` from `state` to avoid confusion with device states.
=> Fix lens mask required component and state

kasa/cli/common.py, kasa/discover.py
Addresses an issue with how `asyncclick` deals with `KeyboardInterrupt` errors. Instead of the `click.main` receiving `KeyboardInterrupt` it receives `CancelledError` because it's a task running inside the loop.
Also ensures that discovery catches the `CancelledError` and closes the http clients.
=> Handle KeyboardInterrupts in the cli better

kasa/transports/sslaestransport.py, tests/transports/test_sslaestransport.py
When `smartcam` devices have failed authentication multiple times due to bad credentials, they go into a blocked state, usually for 30 minutes. This PR handles that as a different error type instead of treating it as a normal `AuthenticationError`.
Example response:
```json
{"data": {"code": -40404, "sec_left": 433}, "error_code": -40401}
```
=> Handle smartcam device blocked response

kasa/httpclient.py, kasa/transports/sslaestransport.py, tests/transports/test_sslaestransport.py
`smartcam` devices can respond with 500 if another session is created from the same host.
A retry should reauthenticate succesfully.
Example response:
```json
{"error_code": -1, "msg": "Check tapo tag failed"}
```
N.B. decryption doesn't always succeed in this instance
=> Treat smartcam 500 errors after handshake as retryable

CHANGELOG.md, pyproject.toml, uv.lock
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.8.1...0.9.0)
**Release highlights:**
- Improvements to Tapo camera support:
- C100, C225, C325WB, C520WS and TC70 now supported.
- Support for motion, person, tamper, and baby cry detection.
- Initial support for Tapo robovacs.
- API extended with `FeatureAttributes` for consumers to test for [supported features](https://python-kasa.readthedocs.io/en/stable/topics.html#modules-and-features).
- Experimental support for Kasa cameras[^1]
[^1]: Currently limited to devices not yet provisioned via the Tapo app - Many thanks to @puxtril!
**Breaking changes:**
- Use DeviceInfo consistently across devices [\#1338](https://github.com/python-kasa/python-kasa/pull/1338) (@sdb9696)
- Add rssi and …
=> Prepare 0.9.0

kasa/transports/klaptransport.py, kasa/transports/sslaestransport.py
This PR makes the exception message on authentication hash mismatches clearer.
I renamed "server" to "device" as that makes more sense for errors that are shown to users.
Related comments:
* https://github.com/home-assistant/core/issues/133164#issuecomment-2567042655
* https://github.com/python-kasa/python-kasa/issues/1351#issuecomment-2569849407
Thanks to @TheHairforce and @ZeliardM for helping spot the issue, I will create a separate PR to update the exception messages to help users encountering the challenge hash mismatch.
=> Improve exception messages on credential mismatches

kasa/smart/smartchilddevice.py
Required for https://github.com/python-kasa/python-kasa/pull/1419 and https://github.com/python-kasa/python-kasa/pull/1418
Fixes [HA issue 133973](https://github.com/home-assistant/core/issues/133973)
=> Add support for Tapo hub-attached switch devices

kasa/feature.py
Instead of simply displaying the enum value, use repr to get a nicer output for the cli.
Was: `Error (vacuum_error): 14`
Now: `Error (vacuum_error): <ErrorCode.DustBinRemoved: 14>`
=> Use repr() for enum values in Feature.__repr__

kasa/protocols/iotprotocol.py, kasa/transports/xortransport.py, tests/protocols/test_iotprotocol.py
`asyncio.TimeoutError` doesn't provide a useful error string so we need to provide something better
```
>>> str(asyncio.TimeoutError())
''
``` 
related issue https://github.com/home-assistant/core/issues/128677
=> Backoff after xor timeout and improve error reporting

CHANGELOG.md, pyproject.toml, uv.lock
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.9.0...0.9.1)
**Release summary:**
- Support for hub-attached wall switches S210 and S220
- Support for older firmware on Tapo cameras
- Bugfixes and improvements
- Add support for Tapo hub-attached switch devices [\#1421](https://github.com/python-kasa/python-kasa/pull/1421) (@sdb9696)
- Use repr\(\) for enum values in Feature.\_\_repr\_\_ [\#1414](https://github.com/python-kasa/python-kasa/pull/1414) (@rytilahti)
- Update SslAesTransport for older firmware versions [\#1362](https://github.com/python-kasa/python-kasa/pull/1362) (@sdb9696)
- T310 not detected with H200 Hub [\#1409](https://github.com/python-kasa/python-kasa/issues/1409)
- Backoff after xor timeout and improve …
=> Prepare 0.9.1

kasa/protocols/smartcamprotocol.py
- This is consistent with `smartprotocol` which raises errors on single calls.
- Will prevent fixtures created via H200 with [inline error codes](https://github.com/python-kasa/python-kasa/blob/master/tests/fixtures/smart/child/S200B(EU)_1.0_1.11.0.json#L88:L89)
=> Raise errors on single smartcam child requests

tests/fakeprotocol_smart.py, tests/fakeprotocol_smartcam.py, tests/fixtureinfo.py, tests/test_devtools.py
Currently the dump_devinfo fixture generation tests do not test generation for hub and their children.
This PR enables tests for `smartcam` hubs and their child fixtures. It does not enable support for `smart` hub fixtures as not all the fixtures currently have the required info. This can be addressed in a subsequent PR.
N.B. This is part of a series of commits being broken out of the `smartcam` children PR: https://github.com/python-kasa/python-kasa/pull/1413
=> Add tests for dump_devinfo parent/child smartcam fixture generation

.readthedocs.yml
Fixes CI build, this key will become mandatory very soon: https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
=> Add required sphinx.configuration

kasa/smart/modules/devicemodule.py, kasa/smart/smartchilddevice.py, kasa/smart/smartdevice.py, kasa/smart/smartmodule.py, kasa/smartcam/modules/device.py, tests/smart/test_smartdevice.py
This PR makes `update_children` default to True for `smart` and `smartcam` devices, and introduces a delay of 24 hours before re-querying hub-attached child modules. In order to allow updates after setting a value the `@allow_update_after` decorator needs to be added to the relevant setters.
=> Update hub children on first update and delay subsequent updates

kasa/device_factory.py, kasa/deviceconfig.py, kasa/discover.py, tests/fixtures/serialization/deviceconfig_camera-aes-https.json, tests/fixtures/serialization/deviceconfig_plug-klap.json, tests/fixtures/serialization/deviceconfig_plug-xor.json, tests/test_discovery.py
`uses_http` is not supposed to be set by consumers. For historical reasons it was a dataclass field so that HomeAssistant could persist and re-use the config dict. This is no longer the case as HA stores the `uses_http` from the `DeviceConfig` directly.
Making `uses_http` a readonly property simplifies the logic in `try_connect_all`. This PR also fixes `try_connect_all` to include `SMART.TAPOROBOVAC` and `IOT.IPCAMERA` as main device types.
**Breaking info** - consumers that relied on `uses_http` to be persisted with `DeviceConfig.to_dict()` will need to store the value separately.
=> Make uses_http a readonly property of device config

kasa/cli/common.py, kasa/cli/device.py, kasa/cli/discover.py, kasa/cli/main.py
Passing the `discover` command with `--host` does not print out the device state. This PR ensures that the `discover` command will print device state unless it is being used to discover devices for subseqeuent processing by a different subcommand.
Fixes https://github.com/python-kasa/python-kasa/issues/1431#issuecomment-2575958545
=> Fix discover cli command with host

kasa/smartcam/modules/alarm.py, kasa/smartcam/modules/babycrydetection.py, kasa/smartcam/modules/camera.py, kasa/smartcam/modules/led.py, kasa/smartcam/modules/lensmask.py, kasa/smartcam/modules/motiondetection.py, kasa/smartcam/modules/persondetection.py, kasa/smartcam/modules/tamperdetection.py, kasa/smartcam/modules/time.py
Hub-attached child camera modules will delay updates 24 hours. This PR adds the `allow_update_after` decorator to the module setters to allow updates after invoking them.
Also ensures that `stream_rtsp_url` and `onvif_url` returns `None` for hub-attached cameras as they don't support streaming.
=> Allow update of camera modules after setting values

kasa/smart/modules/batterysensor.py
Fallback to `is_low` if `at_low_battery` is not available.
Related to #1418 #1419 and https://github.com/home-assistant/core/issues/133973
=> Fallback to is_low for batterysensor's battery_low

kasa/cli/hub.py, kasa/cli/main.py, kasa/feature.py, kasa/module.py, kasa/smart/modules/__init__.py, kasa/smart/modules/childsetup.py, kasa/smart/smartdevice.py, tests/cli/test_hub.py, tests/conftest.py, tests/fakeprotocol_smart.py, tests/fixtures/smart/H100(EU)_1.0_1.5.10.json, tests/smart/modules/test_childsetup.py, tests/smart/test_smartdevice.py, tests/test_cli.py, tests/test_feature.py
This implements "child_quick_setup" that allows pairing and unpairing devices with a hub.
Three new cli commands are added to make the process smooth:
* `kasa hub list` lists current children and their device ids
* `kasa hub pair` searches for unpaired devices and performs pairing after something is discovered. The search ends immediately after finding the first device that can be paired.
* `kasa hub unpair <device_id>`  allows unpairing an existing device.
* `kasa hub supported` to list supported device categories.
=> Add support for pairing devices with hubs

README.md, SUPPORTED.md, devtools/dump_devinfo.py, kasa/cli/discover.py, kasa/device_factory.py, kasa/deviceconfig.py, kasa/discover.py, kasa/protocols/smartprotocol.py, kasa/transports/aestransport.py, kasa/transports/klaptransport.py, kasa/transports/linkietransport.py, kasa/transports/sslaestransport.py, kasa/transports/ssltransport.py, tests/discovery_fixtures.py, tests/fixtures/smart/RV30 Max(US)_1.0_1.2.0.json, tests/smart/modules/test_clean.py, tests/test_cli.py, tests/test_device_factory.py, tests/test_discovery.py
A recent vacuum firmware update (RV30 max) changed to use KLAP instead of "AES" (ssltransport) for encryption.
This PR fixes the issue by using the discovery-reported connection parameters for device communication.
=> Allow https for klaptransport

kasa/discover.py, tests/discovery_fixtures.py, tests/test_device_factory.py
The PR adds `SMARTCAM` devices to the default `discovery_mock` filter and patches `Discover._decrypt_discovery_data` so it doesn't error. To better support testing, the quite involved logic to derive connection parameters from a discovery result, is moved into a static method so it can be used in the tests. This makes the code a lot more readable as well.
Additionally, adding a hub to the list of readme examples mock devices in https://github.com/python-kasa/python-kasa/pull/1470 causes the `on_discovered` callbacks to complete in a different order to the order the devices are declared in the `dict`.
The change of order is non-deterministic and is different based on the environment (the order locally differed from macos CI for example). This PR introduces a queue in the `discovery_mock` …
=> Update test framework to support smartcam device discovery.

kasa/smart/modules/clean.py
Unsure about the naming, but this can apparently happen when the cliff sensors indicate the device cannot move.
=> Add error code 7 for clean module

.pre-commit-config.yaml, devtools/parse_pcap_klap.py, kasa/cli/hub.py, kasa/cli/lazygroup.py, kasa/iot/iotdimmer.py, kasa/iot/modules/lightpreset.py, kasa/protocols/iotprotocol.py, kasa/protocols/smartprotocol.py, kasa/transports/xortransport.py, pyproject.toml, tests/fakeprotocol_smartcam.py, tests/smart/test_smartdevice.py, tests/test_cli.py, tests/transports/test_aestransport.py, tests/transports/test_sslaestransport.py, uv.lock
Ruff 0.9 contains a number of formatter changes for the 2025 style guide. This PR updates to ruff>=0.9.0 and applies the formatter fixes.
https://astral.sh/blog/ruff-v0.9.0
This will reduce the diffs in the [0.10.0 release PR](https://github.com/python-kasa/python-kasa/pull/1473) and keep all the resulting code changes linked to this specific change.
=> Update ruff to 0.9

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml
Currently our CI runs continue after new pushed to pull requests or branches. This PR creates a concurreny group which will cancel in progress workflows after new pushes to pull requests or python-kasa branches. This will improve the performance of the latest CI runs which would otherwise be queued behind previous commit runs.
[github docs](https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs)
N.B. the group expression is the same used by HA core.
Run being cancelled after new push:
=> Cancel in progress CI workflows after new pushes

kasa/smart/modules/energy.py
- Fix: Report `0` instead of `None` for current when current is zero.
- Fix: Report `0` instead of `None` for voltage when voltage is zero (not that this was possible to see).
Changes extracted from #1349
=> Report 0 for instead of None for zero current and voltage

kasa/cli/feature.py, kasa/feature.py, kasa/iot/modules/motion.py, tests/fakeprotocol_iot.py, tests/iot/modules/test_motion.py, tests/test_cli.py, tests/test_feature.py
- Add: ADC value reporting to PIR enabled switches, so that it may be used in polling automations.
- Add: ADC trigger state value reporting, for simpler automations.
- Add: Ability for features to use custom value parsers.
=> Add ADC Value to PIR Enabled Switches

kasa/smart/modules/clean.py, tests/smart/modules/test_clean.py
Convert `carpet_clean_mode` into a switch called `carpet_boost`, as it makes no sense to have an enum for this.
=> Convert carpet_clean_mode to carpet_boost switch

kasa/interfaces/lighteffect.py, kasa/iot/modules/lighteffect.py, kasa/smart/modules/lightstripeffect.py
Fixes [HA Issue 134568](https://github.com/home-assistant/core/issues/134568)
Issue caused when a custom effect has an empty string for a name. Causes the HA `__validate_color_mode` to treat as no effect active:
```py
if not effect or effect == EFFECT_OFF:
if color_mode in supported_color_modes:
return
```
but the integration tests for `!= LightEffect.LIGHT_EFFECTS_OFF` when deciding on the color mode:
```
if effect_module.effect != LightEffect.LIGHT_EFFECTS_OFF:
self._attr_effect = effect_module.effect
self._attr_color_mode = ColorMode.BRIGHTNESS
else:
```
As the effect is in fact on, we should not return empty string for effect name.
=> Do not return empty string for custom light effect name

kasa/interfaces/energy.py, kasa/smart/smartmodule.py, kasa/smartcam/modules/alarm.py, tests/test_common_modules.py
These were missed off in https://github.com/python-kasa/python-kasa/pull/1479. Testing with [HA PR 136642](https://github.com/home-assistant/core/pull/136642) picked this up.
Adding a test case for this highlighted that the decorators currently lose the `Annotated` annotations which `functools.wraps` fixes.
=> Add FeatureAttributes to smartcam Alarm

kasa/smart/modules/dustbin.py, tests/smart/modules/test_dustbin.py
This PR adds a new artificial "Off" mode for dustbin_mode,
which will allow avoiding the need to expose both a toggle and a select in homeassistant.
This changes the behavior of the existing mode selection, as it is not anymore possible to change the mode without activating the auto collection.
* Mode is Off, if auto collection has been disabled
* When setting mode to "Off", this will disable the auto collection
* When setting mode to anything else than "Off", the auto collection will be automatically enabled.
=> dustbin_mode: add 'off' mode for cleaner downstream impl

SUPPORTED.md, tests/fixtures/smart/KS225(US)_1.0_1.1.1.json, tests/fixtures/smart/L930-5(EU)_1.0_1.2.5.json
Added fixture files, one device was added directly into HomeKit, and one device was added through Matter from the obd_src. I'm not sure if that makes a difference for you, but the devices are working correctly through my plug-in with the latest python-kasa 0.10.2.
=> Add KS225(US)_1.0_1.1.1 and L930-5(EU)_1.0_1.2.5

README.md, SUPPORTED.md, tests/fixtures/iot/LB100(US)_1.0_1.8.11.json
The LB100 was already in the device_fixtures.py for tests, but was not listed in the supported devices nor did it have a fixture file.
=> Add LB100(US)_1.0_1.8.11 fixture file
