README.md
Changed because of the organization's name change.
=> change ID of Azure Pipeline

kasa/cli.py, setup.py
=> Set minimum requirement to python 3.7

kasa/smartdevice.py, kasa/smartplug.py, kasa/smartstrip.py
For #37 add in checks for the features and mark the function as property so cli.py and others can just check the value.
=> Check for emeter support on power strips/multiple plug outlets

azure-pipelines.yml, kasa/tests/test_cli.py, requirements_test.txt, tox.ini
This PR starts adding tests to the cli tool outputs.
=> Add (some) tests to the cli tool

kasa/smartdevice.py, kasa/smartplug.py, kasa/smartstrip.py, kasa/tests/conftest.py, kasa/tests/test_fixtures.py
* moves on_since property to smartdevice class, as it is not plug only
* returns None if the value is not available (some bulbs), or if the device is off
=> Return on_since only when its available and the device is on

kasa/smartbulb.py, kasa/tests/newfakes.py
* Add ignore_default to lights to allow setting directly into a specific light state
* Force bulb on when changing the settings
* KL60 does not allow changing the brightness without turning on
* Allow defining brightness for `set_color_temp` (to allow changing both brightness and color temp in a single call)
* Add a couple of new API methods (`get_light_details` and `get_turn_on_behavior`)
=> Improve bulb API, force turn on for all light changes as offline changes are not supported

README.md, devtools/parse_pcap.py
This PR adds a simple script that can be helpful for analyzing traffic captures.
=> Add parse_pcap to devtools, improve readme on contributing

kasa/discover.py
With this PR the device class detection is made purely using the information available in the `system.get_sysinfo` call.
This will make it easier to approach fixing #105
=> Simplify device class detection for discovery, fix hardcoded timeout

README.md, docs/source/cli.rst, docs/source/conf.py, docs/source/index.rst, docs/source/smartbulb.rst, docs/source/smartdevice.rst, docs/source/smartdimmer.rst, docs/source/smartlightstrip.rst, docs/source/smartplug.rst, docs/source/smartstrip.rst
* Add concrete examples for addressing power strip sockets
* Add concrete examples for bulb transitions
* + some minor polishing here and there
Fixes #121
=> Improve cli documentation for bulbs and power strips

.gitignore, kasa/cli.py, kasa/discover.py, kasa/smartdevice.py
Also avoids unnecessary subsequent TCP calls to device
=> Leverage data from UDP discovery to initialize device structure

docs/source/smartstrip.rst
Trivial Fix
Fix documentation and the corresponding command when
turning on/off example.
=> Fix documentation on Smart strips

kasa/smartdevice.py
=> Simplify mac address handling

kasa/smartbulb.py, kasa/smartdevice.py, kasa/tests/conftest.py, kasa/tests/newfakes.py
* Make `set_alias` and time related functions to work on bulbs which use a different service for controlling those.
=> Improve bulb support (alias, time settings)

kasa/__init__.py, kasa/emeterstatus.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/tests/test_emeter.py
Adds the following properties to EmeterStatus for saner API:
* voltage (in V)
* power (in W)
* current (in A)
* total (in kWh)
=> Improve emeterstatus API, move into own module

.github/workflows/ci.yml, .pre-commit-config.yaml, poetry.lock, pyproject.toml
* Remove bandit from CI
* Update poetry.lock&pre-commit-config.yaml
* Remove py3.6 from tests
=> More CI fixes

kasa/cli.py, kasa/discover.py, kasa/tests/conftest.py, kasa/tests/test_discovery.py
* discovered_devices_raw is not anymore available, as that can be accessed directly from the device objects
* test most of the discovery code paths
* some minor cleanups to test handling
* update discovery docs
=> Cleanup discovery & add tests

kasa/protocol.py, kasa/tests/test_protocol.py
closes #216
After, the pf call is gone when debug mode is off:
=> Avoid calling pformat unless debug logging is enabled

kasa/cli.py, kasa/modules/emeter.py, kasa/modules/usage.py, kasa/smartdevice.py
* Consolidate API for both emeter&usage modules
* Add new cli command 'usage' to query usage
Related to #244
=> Improve usage module, consolidate API with emeter

README.md, kasa/smartbulb.py
=> Add KL135 color temperature range

poetry.lock, pyproject.toml
Related to https://github.com/miyakogi/m2r/issues/66
=> Pin mistune to <2.0.0 to fix doc builds

docs/source/cli.rst
This makes the commands more copy&pastable on new devices
=> Minor improvements to onboarding doc

kasa/discover.py
=> Do not crash on discovery on WSL

kasa/cli.py, poetry.lock, pyproject.toml
* Add package_name to version_option(), breaks --version on click < 8
Replaces #282
=> Relax asyncclick version requirement

kasa/protocol.py
Fixes `Call to untyped function "close" in typed context  [no-untyped-call]` when using `mypy --disallow-untyped-calls` and calling the `close()` on `device.protocol`.
=> Improve typing for protocol class

kasa/smartdevice.py
This is the real fix for #295. Targeting modularize branch for the future as we cannot include this into the master without changing the update request.
=> Use device time for on_since calculation

kasa/smartdevice.py
=> Drop microsecond precision for on_since

kasa/modules/__init__.py, kasa/modules/ambientlight.py, kasa/modules/motion.py, kasa/smartdimmer.py
Initial draft implementation for the PIR & LAS modules found in KS220M(US), related to #268
=> Implement motion & ambient light sensor modules for dimmers

kasa/modules/emeter.py, kasa/modules/module.py, kasa/modules/motion.py, kasa/modules/time.py, kasa/smartdevice.py, kasa/smartplug.py, kasa/smartstrip.py
Move more code out from smartdevice class to their proper places.
=> Cleanup smartdevice

.pre-commit-config.yaml, poetry.lock, pyproject.toml
=> Depend on asyncclick >= 8

kasa/smartdevice.py, kasa/tests/test_smartdevice.py
Returns an empty set if no feature information is available
=> Don't crash on devices not reporting features

.github_changelog_generator, CHANGELOG.md, poetry.lock, pyproject.toml
This is the last release prior restructuring the code to enable easier extendability by moving towards more modular architecture.
The most prominent change in this release is the support for effects on light strips.
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.4.1...0.4.2)
- Allow environment variables for discovery target, device type and debug [\#313](https://github.com/python-kasa/python-kasa/pull/313) (@rytilahti)
- Add 'internal\_state' to return the results from the last update query [\#306](https://github.com/python-kasa/python-kasa/pull/306) (@rytilahti)
- Drop microsecond precision for on\_since [\#296](https://github.com/python-kasa/python-kasa/pull/296) (@rytilahti)
- Add effect support for light strips …
=> Release 0.4.2

.pre-commit-config.yaml
Related to https://github.com/psf/black/issues/2964
=> Update pre-commit hooks to fix black in CI

kasa/smartbulb.py, kasa/tests/test_bulb.py
Fixes https://github.com/home-assistant/core/issues/69039
=> Ensure bulb state is restored when turning back on

.pre-commit-config.yaml, docs/source/design.rst, docs/source/index.rst, docs/source/smartbulb.rst, docs/source/smartdevice.rst, docs/source/smartdimmer.rst, docs/source/smartlightstrip.rst, docs/source/smartplug.rst, docs/source/smartstrip.rst, poetry.lock, pyproject.toml
Various documentation updates:
* Add some notes about general lib design, including modules
* Add a note about socket sharing done by the library, add an example how to perform updates in a loop
* Fix module & function links in the common api docs
* Show inherited members on apidocs for individual device classes
* Remove outdated documentation
* Add note about NTP
* Document onboarding process
* Add doc8 to CI
* Bump sphinx version to fix CI, related to https://github.com/readthedocs/readthedocs.org/issues/9038
Fixes #316
Fixes #257
Fixes #129
=> Various documentation updates

kasa/cli.py
=> Avoid discovery on --help

.github/workflows/codeql-analysis.yml
Based on the official template.
=> Add codeql checks

.pre-commit-config.yaml, kasa/discover.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartdimmer.py, kasa/smartstrip.py
Fixes also implicit optionals using https://github.com/hauntsaninja/ as newer mypy versions fail on them.
=> Update pre-commit hooks

devtools/parse_pcap.py, kasa/cli.py, kasa/tests/test_cli.py
This does not add a new dependency, but rather uses rich if it's installed.
Also simplifies some outputs (e.g., using False/True instead of OFF/ON) to make the code more maintainable.
=> Use rich for prettier output, if available

.pre-commit-config.yaml, devtools/parse_pcap.py, docs/source/conf.py, docs/source/index.rst, kasa/tests/newfakes.py, kasa/tests/test_strip.py, poetry.lock, pyproject.toml
See the specific commits for details, basically just some general janitoring.
Closes #359
=> Some release preparation janitoring

CHANGELOG.md, README.md, pyproject.toml
This minor release contains mostly small UX fine-tuning and documentation improvements alongside with bug fixes:
* Improved console tool (JSON output, colorized output if rich is installed)
* Pretty, colorized console output, if `rich` is installed
* Support for configuring bulb presets
* Usage data is now reported in the expected format
* Dependency pinning is relaxed to give downstreams more control
=> Prepare 0.5.1

kasa/cli.py
This will make --json to output relevant contents even when no command is defined (i.e., when calling 'kasa --host <host> --json' or 'kasa --target <bcast> --json'.
Examples:
```
❯ kasa --host 192.168.xx.yye --json| jq '.system.get_sysinfo.model'
"HS110(EU)"
❯ kasa --target 192.168.xx.255 --json | jq 'with_entries(.value |= .system.get_sysinfo.model)'
{
"192.168.xx.yya": "KP303(UK)",
"192.168.xx.yyb": "KP115(EU)",
"192.168.xx.yyc": "KP115(EU)",
"192.168.xx.yyd": "HS110(EU)",
"192.168.xx.yye": "HS110(EU)"
}
```
Spotted in https://github.com/python-kasa/python-kasa/issues/445#issuecomment-1488918435
=> Return result objects for cli discover and implicit 'state'

kasa/smartdimmer.py
Adds configuration options for dimmers. This is untested and likely incomplete, just found from git stash and decided to create a draft PR just in case someone wants to look into this at some point.
=> Add methods to configure dimmer settings

kasa/cli.py, kasa/tests/test_cli.py
=> Add toggle command to cli

.readthedocs.yml
=> Convert readthedocs config to v2

README.md
README.md  Correctly, list partial support on motion switches.
=> Mark KS2{20}M as partially supported

kasa/__init__.py, kasa/cli.py, kasa/credentials.py, kasa/discover.py, kasa/exceptions.py, kasa/smartbulb.py, kasa/smartdevice.py, kasa/smartdimmer.py, kasa/smartlightstrip.py, kasa/smartplug.py, kasa/smartstrip.py, kasa/tests/test_cli.py, kasa/tests/test_smartdevice.py
Add credentials classes and cli support to support future implementation of authenticating protocols.  See https://github.com/python-kasa/python-kasa/pull/477 for discussion
=> Add plumbing for passing credentials to devices

kasa/protocol.py
The code should always be called from the same thread that created the object or we have a thread safety problem.
I believe this check was originally added because the problem was actually in the test suite or a bug in HA which no longer applies
=> Remove code to detect event loop change

CHANGELOG.md, pyproject.toml
The highlights of this maintenance release:
* Support to the alternative discovery protocol and foundational work to support other communication protocols, thanks to @sdb9696.
* Reliability improvements by avoiding overflowing device buffers, thanks to @cobryan05.
* Optimizations for downstream device accesses, thanks to @bdraco.
* Support for both pydantic v1 and v2.
Closes #518
=> Release 0.5.4

README.md
This updates the README to include more resources for curios users and developers as well as some tapo-related links.
=> Add some more external links to README

kasa/protocol.py
=> Set TCP_NODELAY to avoid needless buffering

kasa/device_factory.py, kasa/tests/test_device_factory.py
It seems the move of `connect()` out of discovery dropped the `protocol_class` parameter needed to create devices with different protocols.  I've re-added it pretty much as per before.
=> Re-add protocol_class parameter to connect

kasa/aesprotocol.py, kasa/device_factory.py, kasa/device_type.py, kasa/discover.py, kasa/tapo/tapodevice.py, kasa/tapo/tapoplug.py, kasa/tests/test_discovery.py
Related to https://github.com/python-kasa/python-kasa/pull/499 and https://github.com/python-kasa/python-kasa/discussions/548
=> Add support for the protocol used by TAPO devices and some newer KASA devices.

devtools/dump_devinfo.py, kasa/tests/fixtures/HS100(UK)_4.1_1.1.0.json, kasa/tests/fixtures/smart/P110(UK)_1.0_1.3.0.json
Added `get_temp_humidity_records`, `get_child_device_list` and `get_trigger_logs`
Masked nickname or alias
=> Add new methods to dump_devinfo and mask aliases

kasa/tapo/tapodevice.py
Optimizes the update cycle a bit, as it's doubtful the components change over time
=> Request component_nego only once for tapodevice

kasa/aestransport.py, kasa/exceptions.py, kasa/smartprotocol.py
Broken out from https://github.com/python-kasa/python-kasa/pull/584
=> Add optional error code to exceptions

devtools/README.md, devtools/dump_devinfo.py, kasa/aestransport.py
Fixes #591
Will convert from draft once rebased on top of https://github.com/python-kasa/python-kasa/pull/569
=> Fix dump_devinfo for unauthenticated

kasa/tests/fixtures/smart/L530E(EU)_3.0_1.0.6.json
Update fixture using the dump_devinfo from #597
=> Update L530 aes fixture

kasa/tests/fixtures/smart/P110(EU)_1.0_1.2.3.json
Updated fixture using dump_devinfo from #597
=> Update P110(EU) fixture

kasa/protocol.py
This is very minor, but I noticed this while digging on https://github.com/home-assistant/core/issues/107202 so I figured I'd clean it up
=> Avoid recreating struct each request in legacy protocol

CHANGELOG.md, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.6.0...0.6.0.1)
A patch release to improve the protocol handling.
- Fix httpclient exceptions on read and improve error info [\#655](https://github.com/python-kasa/python-kasa/pull/655) (@sdb9696)
- Improve and document close behavior  [\#654](https://github.com/python-kasa/python-kasa/pull/654) (@bdraco)
**Closed issues:**
- Do not redact OUI for fixtures [\#652](https://github.com/python-kasa/python-kasa/issues/652)
**Merged pull requests:**
- Add l900-5 1.1.0 fixture [\#664](https://github.com/python-kasa/python-kasa/pull/664) (@rytilahti)
- Add fixtures with new MAC mask [\#661](https://github.com/python-kasa/python-kasa/pull/661) (@sdb9696)
- Make close behaviour consistent across new protocols and …
=> Release 0.6.0.1

docs/source/design.rst, kasa/protocol.py
Addresses [comment here](https://github.com/python-kasa/python-kasa/pull/557#discussion_r1412851451) and elsewhere.
=> Add protocol and transport documentation

kasa/tests/conftest.py, kasa/tests/fixtures/smart/P135(US)_1.0_1.0.5.json
This device is a dimmer but we currently treat it as a on/off
=> Add P135 fixture

.github/workflows/ci.yml, README.md, devtools/check_readme_vs_fixtures.py
This will add a new linting checks to verify that the README file mentions all models with fixtures.
Also changed the section structure a bit.
=> Check README for supported models

devtools/dump_devinfo.py
A `batch_size` of 1 will avoid `multiRequest` completely
=> Make dump_devinfo request batch size configurable

kasa/aestransport.py, kasa/klaptransport.py, kasa/protocol.py, kasa/tests/test_aestransport.py, kasa/tests/test_klapprotocol.py
=> Try default tapo credentials for klap and aes

docs/source/cli.rst
Provisioning pends on fixing #616 (or manually commenting out the failing queries).
Fixes #565.
=> Document authenticated provisioning

kasa/cli.py
reverts and replaces https://github.com/python-kasa/python-kasa/pull/703
=> Replace rich formatting stripper

kasa/klaptransport.py, kasa/protocol.py
=> Use hashlib in place of hashes.Hash

kasa/smart/modules/__init__.py, kasa/smart/modules/lighttransitionmodule.py, kasa/smart/smartdevice.py, kasa/tests/fakeprotocol_smart.py
Allows enabling and disabling smooth transitions on devices that support it.
=> Add smartdevice module for smooth transitions

kasa/klaptransport.py, kasa/tests/test_klapprotocol.py
Fixes issue https://github.com/python-kasa/python-kasa/issues/784
=> Retry query on 403 after successful handshake

devtools/helpers/smartrequests.py, kasa/iot/modules/ambientlight.py
Add new feature for AmbientLight sensor module. 
```{'get_current_brt': {'value': 26, 'err_code': 0}```
```== Laundry Room - KS220M(US) ==
Host: 192.168.2.107
Port: 9999
Device state: False
== Generic information ==
Time:         2024-02-22 11:35:58 (tz: {'index': 13, 'err_code': 0}
Hardware:     1.0
Software:     1.0.10 Build 230113 Rel.151032
MAC (rssi):   xx:xx:xx:xx:xx (-63)
Location:     {'latitude': xxx, 'longitude': xxx}
== Device specific information ==
Brightness: 100
== Features == 
LED (led): True
Cloud connection (cloud_connection): True
Ambient Light (ambient_light): 29
== Modules ==
+ <Module Schedule (schedule) for 192.168.2.107>
+ <Module Usage (schedule) for 192.168.2.107>
+ <Module Antitheft (anti_theft) for 192.168.2.107>
+ <Module Time (time) for 192.168.2.107>
+ …
```
=> Add feature for ambient light sensor

kasa/tests/fixtures/smart/L530E(EU)_3.0_1.1.6.json
Including on_off_gradually upgrade 1 -> 3 which breaks the current impl.
=> Add updated l530 fixture 1.1.6

README.md, devtools/dump_devinfo.py, devtools/helpers/smartrequests.py, kasa/smart/modules/firmware.py, kasa/tests/conftest.py, kasa/tests/fakeprotocol_smart.py, kasa/tests/fixtures/smart/H100(EU)_1.0_1.2.3.json, kasa/tests/fixtures/smart/H100(EU)_1.0_1.5.5.json
One direct out of the box, another with upgraded fw & t315
=> Add H100 fixtures

kasa/tests/fixtures/smart/P110(EU)_1.0_1.0.7.json
By courtesy of @pplucky (#797).
=> Add fixture for P110 sw 1.0.7

kasa/smart/modules/__init__.py, kasa/smart/modules/brightness.py, kasa/smart/smartmodule.py, kasa/tests/device_fixtures.py, kasa/tests/test_feature_brightness.py
Add module for controlling the brightness.
=> Add brightness module

kasa/tests/device_fixtures.py, kasa/tests/fixtureinfo.py
This will allow:
1. Fixture parameters to be combined across different filter types to combine feature testing across SMART & IOT.
2. Dynamic parametrization of device types instead of hardcoding models in `conftest`
=> Update test framework for dynamic parametrization

kasa/smart/modules/firmware.py
The v1 of firmware does not support changing the auto update setting, this makes it so that it isn't requested in that case.
Fixes https://github.com/python-kasa/python-kasa/issues/819
=> Add support for firmware module v1

.github/workflows/ci.yml
Do not try to upload coverage for pypy which is run without coverage.
=> Do not try coverage upload for pypy

.github/actions/setup/action.yaml
Fixes the pypy 3.9 CI issues on macos since the recent macos-latest update.
=> Fix pypy39 CI cache on macos

kasa/smart/modules/__init__.py, kasa/smart/modules/waterleak.py, kasa/smart/smartchilddevice.py, kasa/tests/smart/modules/test_waterleak.py
This adds support for waterleak sensor child device.
TODO:
This is tested to work, but we are missing fixture.
Related to #875
=> Add support for waterleak sensor (T300)

kasa/smart/modules/battery.py
At least some firmware versions of T110 are known not to report this.
Related to #877
=> Add 'battery_percentage' only when it's available

kasa/smart/modules/firmware.py, kasa/tests/fakeprotocol_smart.py, kasa/tests/smart/modules/test_firmware.py
* Expose current and latest firmware as features
* Provide API to get information about available firmware updates (e.g., changelog, release date etc.)
* Implement updating the firmware
=> Improve smartdevice update module

CHANGELOG.md, pyproject.toml
First dev release for 0.7.0: add module support for SMART devices, support for introspectable device features and refactoring the library
=> Prepare 0.7.0.dev0

CHANGELOG.md, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.7.0.dev0...0.7.0.dev1)
- Fix set\_state for common light modules [\#929](https://github.com/python-kasa/python-kasa/pull/929) (@sdb9696)
- Add state feature for iot devices [\#924](https://github.com/python-kasa/python-kasa/pull/924) (@rytilahti)
=> Prepare 0.7.0.dev1

.github_changelog_generator, CHANGELOG.md, RELEASING.md, poetry.lock, pyproject.toml
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.7.0.dev2...0.7.0.dev3)
- Fix switching off light effects for iot lights strips [\#961](https://github.com/python-kasa/python-kasa/pull/961) (@sdb9696)
- Add state features to iot strip sockets [\#960](https://github.com/python-kasa/python-kasa/pull/960) (@sdb9696)
- Ensure http delay logic works during default login attempt [\#959](https://github.com/python-kasa/python-kasa/pull/959) (@sdb9696)
- Fix fan speed level when off and derive smart fan module from common fan interface [\#957](https://github.com/python-kasa/python-kasa/pull/957) (@sdb9696)
- Require update in cli for wifi commands [\#956](https://github.com/python-kasa/python-kasa/pull/956) (@rytilahti)
**Project maintenance:**
- Use freezegun …
=> Prepare 0.7.0.dev3

kasa/feature.py
To prevent untyped call mypy errors in consumers
=> Add type hints to feature set_value

kasa/iot/iotdevice.py, kasa/iot/iotstrip.py, kasa/smart/smartdevice.py
This allows them to displayed in HA without errors.
=> Add timezone to on_since attributes

kasa/cli.py, kasa/tests/test_cli.py
It is unwise to allow executing commands on multiple devices at the same time, so this PR will show an error if one tries to do this mistakenly.
Closes #71
Obsoletes #392
=> Disallow non-targeted device commands

README.md, docs/source/codeinfo.md, docs/source/guides.md, docs/source/guides/connect.md, docs/source/guides/device.md, docs/source/guides/discover.md, docs/source/guides/energy.md, docs/source/guides/feature.md, docs/source/guides/light.md, docs/source/guides/module.md, docs/source/guides/strip.md, docs/source/reference.md, docs/source/tutorial.md, docs/tutorial.py, kasa/device.py, kasa/feature.py, kasa/interfaces/light.py, kasa/interfaces/lighteffect.py, kasa/interfaces/lightpreset.py, kasa/module.py, kasa/smart/modules/childdevice.py, kasa/tests/test_readme_examples.py
And include a header note on all examples about async
https://python-kasa--968.org.readthedocs.build/en/968/guides.html
=> Update docs with more howto examples

kasa/cli.py, kasa/tests/test_cli.py
Closes https://github.com/python-kasa/python-kasa/issues/958
=> Fix to call update when only --device-family passed to cli

README.md
UX first approach for both cli & library users, to get you directly started with the basics.
Fixes #979
=> Update README to be more approachable for new users

README.md
* Update cli outputs
* Remove tapo support statement
* Fix some minor nits
=> Cleanup README to use the new cli format

kasa/cli.py, kasa/tests/test_cli.py
* Avoid unnecessary indentation of elements, now only the child device information is indented
* Use _echo_all_features consistently for both `state` and `feature`
* Avoid discovery log message which brings no extra value
* Hide location by default
```
== Smart Hub - H100 ==
Host: 192.168.xx
Port: 80
Device state: False
Time:         2024-06-22 15:49:27+02:00 (tz: {'timezone': 'CEST'}
Hardware:     1.0
Software:     1.5.10 Build 240207 Rel.175759
MAC (rssi):   3C:52:A1:xxx (-62)
== Information ==
Signal Level (signal_level): 2
Overheated (overheated): False
Alarm (alarm): False
Alarm source (alarm_source): None
Cloud connection (cloud_connection): False
Update available (update_available): None
Device time (device_time): 2024-06-22 15:49:27+02:00
== Configuration ==
Alarm sound …
```
=> Cleanup cli output

kasa/smart/modules/frostprotection.py
This provides the same functionality as the state in `TemperatureControl`, so we should not expose this separately.
=> Remove frost_protection feature

kasa/smartprotocol.py
=> Disable multi-request on unknown errors

devtools/helpers/smartrequests.py, kasa/smart/modules/autooff.py, kasa/smart/modules/batterysensor.py, kasa/smart/modules/cloud.py, kasa/smart/modules/devicemodule.py, kasa/smart/modules/firmware.py, kasa/smart/modules/frostprotection.py, kasa/smart/modules/humiditysensor.py, kasa/smart/modules/lightpreset.py, kasa/smart/modules/lighttransition.py, kasa/smart/modules/reportmode.py, kasa/smart/modules/temperaturesensor.py, kasa/smart/smartdevice.py, kasa/smart/smartmodule.py, kasa/smartprotocol.py, kasa/tests/test_smartdevice.py, kasa/tests/test_smartprotocol.py
Cherry pick of https://github.com/python-kasa/python-kasa/pull/1036 to patch
=> Handle module errors more robustly and add query params to light preset and transition

SUPPORTED.md, kasa/tests/fixtures/smart/KS225(US)_1.0_1.1.0.json
Many thanks to @gimpy88 for the fixture here https://github.com/python-kasa/python-kasa/issues/1033
=> Add KS225(US) v1.1.0 fixture

SUPPORTED.md, kasa/tests/fixtures/KS200M(US)_1.0_1.0.11.json
Split out from https://github.com/python-kasa/python-kasa/pull/1037. Many thanks @gimpy88!
=> Add KS200M(US) v1.0.11 fixture

SUPPORTED.md, kasa/tests/fixtures/smart/KS205(US)_1.0_1.1.0.json
Add updated KS205(US) v1.1.0 fixture. Firmware now uses KLAP.
=> Add KS205(US) v1.1.0 fixture

pyproject.toml
To reflect the latest release from patch.
=> Bump project version to 0.7.0.3

pyproject.toml
To bring it up with current patch release version
=> Bump version to 0.7.0.4

SUPPORTED.md, kasa/tests/fixtures/KP405(US)_1.0_1.0.6.json
Adding fixture file for KP405. @rytilahti
=> Add fixture file for KP405 fw 1.0.6

kasa/discover.py, kasa/iot/iotdevice.py, kasa/iotprotocol.py, kasa/klaptransport.py, kasa/protocol.py, kasa/smart/smartdevice.py, kasa/smartprotocol.py, kasa/tests/discovery_fixtures.py, kasa/tests/test_discovery.py, kasa/tests/test_protocol.py, kasa/tests/test_smartprotocol.py, kasa/xortransport.py
Redacts sensitive data when debug logging device responses such as mac, location and usernames
=> Redact sensitive info from debug logs

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, CHANGELOG.md
**This PR needs to be merged with a merge commit**
=> Merge patch into master

kasa/iot/iotbulb.py, kasa/iot/modules/lighteffect.py, kasa/module.py, kasa/smart/modules/lightstripeffect.py, kasa/tests/fakeprotocol_iot.py, kasa/tests/fakeprotocol_smart.py, kasa/tests/smart/modules/test_light_strip_effect.py, kasa/tests/test_common_modules.py
Fixes [HA Issue](https://github.com/home-assistant/core/issues/122401#issuecomment-2254183384) where the brightness of the light effect is set properly on the light effect but read back from the light.
=> Fix iot light effect brightness

kasa/smart/modules/alarm.py
Fixes typing issues for https://github.com/home-assistant/core/pull/124934
=> Add missing type hints to alarm module

kasa/cli/device.py, kasa/cli/main.py, kasa/tests/test_cli.py
Allow reseting devices to factory settings using the cli: `kasa device factory-reset`
=> Add factory-reset command to cli

SUPPORTED.md, kasa/tests/fixtures/KL135(US)_1.0_1.0.15.json
By courtesy of @jhemak: https://github.com/home-assistant/core/issues/126300#issuecomment-2364640319
=> Add fixture for KL135(US) fw 1.0.15

kasa/smart/smartchilddevice.py
This will facilitate distuingishing between smart and smart camera child devices.
=> Expose smart child device map as a class constant

kasa/experimental/sslaestransport.py
Having this dependency causes conflicts with HA and it's not actually needed as we can use the `ssl.SslContext` directly.
Also updates to run in an executor as it does some IO.
=> Drop urllib3 dependency and create ssl context in executor thread

kasa/smart/smartchilddevice.py
Also, improve device type warning on unknown devices
=> Add motion sensor to known categories

kasa/tests/fixtures/experimental/H200(US)_1.0_1.3.6.json
Many thanks to @SirWaddles for the fixture and testing!
=> Add H200 experimental fixture

SUPPORTED.md, kasa/tests/fixtures/smart/child/T110(US)_1.0_1.9.0.json, kasa/tests/fixtures/smart/child/T310(US)_1.0_1.5.0.json, kasa/tests/fixtures/smart/child/T315(US)_1.0_1.8.0.json
Many thanks to @SirWaddles for the fixtures!
=> Add T110(US), T310(US) and T315(US) sensor fixtures

kasa/cli/discover.py, kasa/tests/test_cli.py
Will output a concise table:
```
HOST            DEVICE FAMILY        ENCRYPT ALIAS
192.168.1.2     UNSUPPORTED DEVICE
192.168.1.3     SMART.TAPOBULB       KLAP    Some room alias
192.168.1.4     IOT.SMARTPLUGSWITCH  XOR     Some room alias
192.168.1.5     SMART.TAPOBULB       AES     Some room alias
192.168.1.6     SMART.TAPOBULB       KLAP    Some room alias
192.168.1.7     SMART.TAPOPLUG       KLAP    Some room alias
192.168.1.8     IOT.SMARTPLUGSWITCH  KLAP    Some room alias
192.168.1.9     SMART.TAPOBULB       AES     Some room alias
192.168.1.10    IOT.SMARTPLUGSWITCH  XOR     Some room alias
192.168.1.11    IOT.SMARTPLUGSWITCH  XOR     Some room alias
192.168.1.12    IOT.SMARTPLUGSWITCH  XOR     Some room alias
192.168.1.13    IOT.SMARTPLUGSWITCH  KLAP    Some room alias …
```
=> Add discovery list command to cli

kasa/discover.py, kasa/experimental/sslaestransport.py, kasa/tests/test_sslaestransport.py
Fixes a bug with the default username logic and adds tests for the transport.
=> Fix SslAesTransport default login and add tests

kasa/iot/iotbulb.py, kasa/smart/modules/color.py
Not sure if we need to do something similar for `ColorTempRange(*ct_range)` although I don't think the `__new__` works with the expansion.
=> Make HSV NamedTuple creation more efficient

devtools/parse_pcap_klap.py
I need to work out why the RELEASING.md steps aren't catching the new mypy errors after updating all dependencies...
=> Fix mypy errors in parse_pcap_klap

kasa/iot/modules/ambientlight.py, kasa/tests/iot/modules/test_ambientlight.py
This PR adds a setting to control the ambient light enabled/disabled.
Also fixes the getters, related to #1174
=> Expose ambient light setting for iot dimmers

kasa/tests/fixtures/smart/child/S200B(US)_1.0_1.12.0.json, kasa/tests/fixtures/smart/child/T110(US)_1.0_1.9.0.json, kasa/tests/fixtures/smart/child/T310(US)_1.0_1.5.0.json, kasa/tests/fixtures/smart/child/T315(US)_1.0_1.8.0.json, kasa/tests/fixtures/smartcamera/H200(US)_1.0_1.3.6.json
Thanks @SirWaddles for the updated fixtures!
=> Update smartcamera fixtures from latest dump_devinfo

kasa/tests/fixtures/smartcamera/TC65_1.0_1.3.9.json
Contains now the component listing, thanks to #1223
=> Update TC65 fixture

README.md, SUPPORTED.md, kasa/tests/fixtures/smart/L630(EU)_1.0_1.1.2.json
By courtesy of @firstofmany52: https://github.com/python-kasa/python-kasa/discussions/1150#discussioncomment-11203279
=> Add L630 fixture

kasa/device.py, kasa/iot/iotdevice.py, kasa/smart/smartchilddevice.py, kasa/smart/smartdevice.py, kasa/smartcamera/smartcamera.py, tests/test_childdevice.py, tests/test_device.py
Fixes https://github.com/python-kasa/python-kasa/issues/1262
=> Fix repr for device created with no sysinfo or discovery info"

kasa/iot/modules/cloud.py, tests/fakeprotocol_iot.py, tests/iot/modules/test_cloud.py
Breaking change as the CloudInfo interface is changing to snake case for consistency with the rest of the library.
=> Migrate iot cloud module to mashumaro

kasa/cli/discover.py, pyproject.toml, uv.lock
Remove pydantic dependency in favor of mashumaro.
=> Remove pydantic dependency

kasa/deviceconfig.py
Related explanation: https://github.com/Fatal1ty/mashumaro/issues/264
=> Simplify omit http_client in DeviceConfig serialization

kasa/device_factory.py, kasa/discover.py, tests/discovery_fixtures.py, tests/test_device_factory.py
=> Make discovery on unsupported devices less noisy

kasa/smartcamera/modules/camera.py, tests/smartcamera/test_smartcamera.py
This will allow HA to use the stored credentials_hash to access the live stream
=> Use credentials_hash for smartcamera rtsp url

kasa/smartcam/smartcamdevice.py, tests/smartcam/test_smartcamdevice.py, tests/test_device.py
Fixes [HA issue 132420](https://github.com/home-assistant/core/issues/132420)
=> Fix smartcam missing device id

kasa/smart/smartdevice.py, kasa/smartcam/smartcamdevice.py
Fixes issue mentioned in comments in issue https://github.com/python-kasa/python-kasa/issues/1341#issuecomment-2521103516
=> Fix update errors on hubs with unsupported children

devtools/dump_devinfo.py
Fixes:
- Decrypted discovery data saved under `discovery_result` instead of `result`
- `smart` child data not redacted
- `smartcam` child component list `device_id` not `SCRUBBED`
=> Miscellaneous minor fixes to dump_devinfo

kasa/module.py, kasa/smartcam/modules/__init__.py, kasa/smartcam/modules/camera.py, kasa/smartcam/modules/lensmask.py, kasa/smartcam/smartcamdevice.py, tests/smartcam/test_smartcamdevice.py
Ensure we do not error with devices that do not have the `lens_mask` component.
=> Add LensMask module to smartcam

README.md, SUPPORTED.md, tests/fixtures/smartcam/C325WB(EU)_1.0_1.1.17.json
Many thanks to @timr49 for the fixture!
=> Add C325WB(EU) 1.0 1.1.17 Fixture

README.md, SUPPORTED.md, tests/fixtures/smartcam/TC70_3.0_1.3.11.json
Many thanks to @allanbeth for the fixture!
=> Add TC70 3.0 1.3.11 fixture

kasa/smartcam/modules/__init__.py, kasa/smartcam/modules/babycrydetection.py, kasa/smartcam/modules/motion.py, kasa/smartcam/modules/motiondetection.py, kasa/smartcam/modules/persondetection.py, kasa/smartcam/modules/tamperdetection.py, kasa/smartcam/smartcammodule.py, tests/smartcam/modules/test_babycrydetection.py, tests/smartcam/modules/test_motiondetection.py, tests/smartcam/modules/test_persondetection.py, tests/smartcam/modules/test_tamperdetection.py
- Motion detection
- Person detection
- Tamper detection
- Baby Cry Detection
=> Add smartcam detection modules

SUPPORTED.md, tests/fixtures/smart/P135(US)_1.0_1.2.0.json
Thanks for the fixture @nakanaela!
=> Add P135 1.0 1.2.0 fixture

README.md, SUPPORTED.md, tests/fixtures/smartcam/C225(US)_2.0_1.0.11.json
Thanks for the fixture @nakanaela!
=> Add C225(US) 2.0 1.0.11 fixture

SUPPORTED.md, devtools/generate_supported.py, tests/fixtures/smartcam/C210_2.0_1.3.11.json
Many thanks @allanbeth for the fixture!
=> Add C210 2.0 1.3.11 fixture

kasa/cli/discover.py
=> Fix incorrect obd src echo

kasa/protocols/smartprotocol.py
`alias` and `ext_addr` will be found on `smartcam` child devices
=> Add more redactors for smartcams

README.md, SUPPORTED.md, tests/fixtures/smartcam/H200(EU)_1.0_1.3.6.json, tests/fixtures/smartcam/child/D230(EU)_1.20_1.1.19.json
Thanks to @etmmvdp for the fixture!
=> Add D230(EU) 1.20 1.1.19 fixture

devtools/helpers/smartrequests.py, kasa/module.py, kasa/smart/modules/__init__.py, kasa/smart/modules/speaker.py, kasa/smart/modules/vacuumspeaker.py, tests/fakeprotocol_smart.py, tests/fixtures/smart/RV20 Max Plus(EU)_1.0_1.0.7.json, tests/smart/modules/test_speaker.py
Implements `speaker` and adds the following features:
* `volume`  to control the speaker volume
* `locate` to play "I'm here sound"
=> Add vacuum speaker controls

kasa/smart/modules/clean.py, tests/smart/modules/test_clean.py
Adds the following new feature:
```
== Configuration ==
Clean count (clean_count): 1 (range: 1-3)
```
=> Add setting to change clean count

kasa/module.py, kasa/smart/modules/__init__.py, kasa/smart/modules/mop.py, tests/smart/modules/test_mop.py
Adds the following new features:
```
Mop water level (mop_waterlevel): *Disable* Low Medium High
Mop attached (mop_attached): True
```
=> Add mop module

kasa/smart/modules/childdevice.py, kasa/smart/smartchilddevice.py, kasa/smart/smartdevice.py, kasa/smartcam/modules/childdevice.py, kasa/smartcam/smartcamdevice.py, tests/fakeprotocol_smart.py, tests/fakeprotocol_smartcam.py, tests/smart/test_smartdevice.py
- **Make fake transport get child device queries easily patcheable**
- **Enable dynamic hub child creation and deletion on update**
=> Enable dynamic hub child creation and deletion on update

devtools/helpers/smartrequests.py, kasa/smart/modules/clean.py, tests/fixtures/smart/RV20 Max Plus(EU)_1.0_1.0.7.json, tests/smart/modules/test_clean.py
Add new setting:
```
== Configuration ==
Carpet clean mode (carpet_clean_mode): Normal *Boost*
```
=> Add setting to change carpet clean mode

devtools/helpers/smartrequests.py, kasa/module.py, kasa/smart/modules/__init__.py, kasa/smart/modules/childlock.py, tests/fixtures/smart/RV20 Max Plus(EU)_1.0_1.0.7.json, tests/smart/modules/test_childlock.py
Add new configuration feature:
```
Child lock (child_lock): False
```
=> Add childlock module for vacuums

docs/tutorial.py, kasa/cli/main.py, kasa/cli/vacuum.py, kasa/feature.py, kasa/module.py, kasa/smart/modules/__init__.py, kasa/smart/modules/cleanrecords.py, kasa/smart/modules/vacuumrecords.py, kasa/smart/smartdevice.py, tests/cli/test_vacuum.py, tests/fixtures/smart/RV20 Max Plus(EU)_1.0_1.0.7.json, tests/smart/modules/test_cleanrecords.py, tests/smart/test_smartdevice.py
Adds the following sensors:
```
Total area cleaned (total_clean_area): 47 <AreaUnit.Sqm: 0>
Total time cleaned (total_clean_time): 0:01:17
Last area cleaned (last_clean_area): 16 <AreaUnit.Sqm: 0>
Last time cleaned (last_clean_time): 0:00:25
Total clean count (total_clean_count): 3
Last clean timestamp (last_clean_timestamp): 2025-01-13 20:45:45
```
=> Add support for cleaning records

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml
This will enable for PRs that we create to other branches, i.e. https://github.com/python-kasa/python-kasa/pull/1470
=> Enable CI workflow on PRs to feat/ fix/ and janitor/

README.md, SUPPORTED.md, tests/fixtures/smart/D100C(US)_1.0_1.1.3.json
Many thanks @steveredden for the fixture!
=> Add D100C(US) 1.0 1.1.3 fixture

README.md, SUPPORTED.md, tests/fixtures/smartcam/D130(US)_1.0_1.1.9.json
Many thanks @steveredden for the fixture!
=> Add D130(US) 1.0 1.1.9 fixture

kasa/smart/modules/childsetup.py, kasa/smart/smartdevice.py, kasa/smartcam/modules/__init__.py, kasa/smartcam/modules/childsetup.py, kasa/smartcam/smartcamdevice.py, kasa/smartcam/smartcammodule.py, tests/fakeprotocol_smartcam.py, tests/smartcam/modules/test_childsetup.py, tests/test_cli.py, tests/test_feature.py
Adds the childsetup module for smartcam hubs to allow pairing and unpairing child devices
=> Add childsetup module to smartcam hubs

kasa/smart/modules/dustbin.py
Fixes the category for the empty dustbin action.
=> Change category for empty dustbin feature from Primary to Config

kasa/module.py, tests/iot/test_iotdevice.py, tests/smart/modules/test_fan.py, tests/smart/test_smartdevice.py, tests/test_common_modules.py
See https://github.com/python-kasa/python-kasa/pull/1470#discussion_r1926049101
=> Add module.device to the public api

kasa/iot/iotdimmer.py, kasa/iot/modules/__init__.py, kasa/iot/modules/dimmer.py, kasa/module.py, tests/iot/modules/test_dimmer.py
- Add: Support for configuring minimum dimming level.
- Add: Support for configuring dimmer ramp rate.
- Add: Support for configuring dimmer gentle fade time.
- Add: Support for configuring dimmper fade time.
=> Add Dimmer Configuration Support

.pre-commit-config.yaml, CHANGELOG.md, pyproject.toml, uv.lock
[Full Changelog](https://github.com/python-kasa/python-kasa/compare/0.10.0...0.10.1)
**Release summary:**
Small patch release for bugfixes
- dustbin\_mode: add 'off' mode for cleaner downstream impl [\#1488](https://github.com/python-kasa/python-kasa/pull/1488) (@rytilahti)
- Add Dimmer Configuration Support [\#1484](https://github.com/python-kasa/python-kasa/pull/1484) (@ryenitcher)
- Do not return empty string for custom light effect name [\#1491](https://github.com/python-kasa/python-kasa/pull/1491) (@sdb9696)
- Add FeatureAttributes to smartcam Alarm [\#1489](https://github.com/python-kasa/python-kasa/pull/1489) (@sdb9696)
**Project maintenance:**
- Add module.device to the public api …
=> Prepare 0.10.1

README.md, SUPPORTED.md, tests/fixtures/smart/L530B(EU)_3.0_1.1.9.json
Thanks for the fixture @LXGaming!
=> Add L530B(EU) 3.0 1.1.9 fixture

README.md, SUPPORTED.md, tests/fixtures/smart/L530B(EU)_3.0_1.1.9.json, tests/fixtures/smartcam/C110(EU)_2.0_1.4.3.json
Thanks for the fixture @LXGaming!
=> Add C110(EU) 2.0 1.4.3 fixture

docs/source/guides/energy.md
=> Add a note to emeter guide being kasa-only
